<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-11 09:20:59                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoVkRequest extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'method' => LightMetaProperty::fill(new LightMetaProperty(), 'method', null, 'string', null, null, true, true, false, null, null),
				'accessToken' => LightMetaProperty::fill(new LightMetaProperty(), 'accessToken', 'access_token', 'string', null, null, true, true, false, null, null),
				'groupId' => LightMetaProperty::fill(new LightMetaProperty(), 'groupId', 'group_id', 'string', null, null, false, true, false, null, null),
				'friendsOnly' => LightMetaProperty::fill(new LightMetaProperty(), 'friendsOnly', 'friends_only', 'string', null, null, false, true, false, null, null),
				'fromGroup' => LightMetaProperty::fill(new LightMetaProperty(), 'fromGroup', 'from_group', 'boolean', null, null, false, true, false, null, null),
				'message' => LightMetaProperty::fill(new LightMetaProperty(), 'message', null, 'string', null, null, false, true, false, null, null),
				'attachments' => LightMetaProperty::fill(new LightMetaProperty(), 'attachments', null, 'string', null, null, false, true, false, null, null),
				'imgUrl' => LightMetaProperty::fill(new LightMetaProperty(), 'imgUrl', 'img_url', 'string', null, null, false, true, false, null, null)
			);
		}
	}
?>