<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-08 10:10:45                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformUsersUser extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PlatformUsersUser', 8, true, true, false, null, null),
				'email' => LightMetaProperty::fill(new LightMetaProperty(), 'email', null, 'string', null, 128, true, true, false, null, null),
				'password' => LightMetaProperty::fill(new LightMetaProperty(), 'password', null, 'string', null, 256, true, true, false, null, null),
				'nickname' => LightMetaProperty::fill(new LightMetaProperty(), 'nickname', null, 'string', null, 32, false, true, false, null, null),
				'deleted' => LightMetaProperty::fill(new LightMetaProperty(), 'deleted', null, 'boolean', null, null, true, true, false, null, null),
				'moderation' => LightMetaProperty::fill(new LightMetaProperty(), 'moderation', null, 'boolean', null, null, true, true, false, null, null),
				'banned' => LightMetaProperty::fill(new LightMetaProperty(), 'banned', null, 'boolean', null, null, false, true, false, null, null)
			);
		}
	}
?>