<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-28 11:01:03                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformSocialFlow extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PlatformSocialFlow', 8, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 256, true, true, false, null, null),
				'accessToken' => LightMetaProperty::fill(new LightMetaProperty(), 'accessToken', 'access_token', 'string', null, null, false, true, false, null, null),
				'secretKey' => LightMetaProperty::fill(new LightMetaProperty(), 'secretKey', 'secret_key', 'string', null, null, false, true, false, null, null),
				'deleted' => LightMetaProperty::fill(new LightMetaProperty(), 'deleted', null, 'boolean', null, null, false, true, false, null, null)
			);
		}
	}
?>