<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-27 11:30:08                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformUsersAdminProfile extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PlatformUsersAdminProfile', 8, true, true, false, null, null),
				'admin' => LightMetaProperty::fill(new LightMetaProperty(), 'admin', 'admin_id', 'identifier', 'PlatformUsersAdmin', null, true, false, false, 1, 3),
				'lastName' => LightMetaProperty::fill(new LightMetaProperty(), 'lastName', 'last_name', 'string', null, 64, true, true, false, null, null),
				'firstName' => LightMetaProperty::fill(new LightMetaProperty(), 'firstName', 'first_name', 'string', null, 64, true, true, false, null, null),
				'middleName' => LightMetaProperty::fill(new LightMetaProperty(), 'middleName', 'middle_name', 'string', null, 64, true, true, false, null, null),
				'createdAt' => LightMetaProperty::fill(new LightMetaProperty(), 'createdAt', 'created_at', 'timestampTZ', 'TimestampTZ', null, true, true, false, null, null),
				'passwordExpiresTime' => LightMetaProperty::fill(new LightMetaProperty(), 'passwordExpiresTime', 'password_expires_time', 'timestampTZ', 'TimestampTZ', null, true, true, false, null, null),
				'alias' => LightMetaProperty::fill(new LightMetaProperty(), 'alias', null, 'hstore', 'Hstore', null, false, true, false, null, null),
				'settings' => LightMetaProperty::fill(new LightMetaProperty(), 'settings', null, 'hstore', 'Hstore', null, false, true, false, null, null),
				'status' => LightMetaProperty::fill(new LightMetaProperty(), 'status', null, 'string', null, 256, true, true, false, null, null)
			);
		}
	}
?>