<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-22 11:29:33                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformLogsAdminAuthLogsRequest extends ProtoPlatformBaseRequest
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'systemUser' => LightMetaProperty::fill(new LightMetaProperty(), 'systemUser', 'system_user', 'boolean', null, null, false, true, false, null, null),
						'admin' => LightMetaProperty::fill(new LightMetaProperty(), 'admin', 'admin_id', 'identifier', 'PlatformUsersAdmin', null, false, false, false, 1, 3),
						'entryAt' => LightMetaProperty::fill(new LightMetaProperty(), 'entryAt', 'entry_at', 'timestampTZ', 'TimestampTZ', null, false, true, false, null, null),
						'login' => LightMetaProperty::fill(new LightMetaProperty(), 'login', null, 'string', null, 64, false, true, false, null, null),
						'password' => LightMetaProperty::fill(new LightMetaProperty(), 'password', null, 'string', null, 256, false, true, false, null, null),
						'ip' => LightMetaProperty::fill(new LightMetaProperty(), 'ip', null, 'string', null, 15, false, true, false, null, null),
						'captcha' => LightMetaProperty::fill(new LightMetaProperty(), 'captcha', null, 'string', null, 16, false, true, false, null, null),
						'blockedIp' => LightMetaProperty::fill(new LightMetaProperty(), 'blockedIp', 'blocked_ip', 'boolean', null, null, false, true, false, null, null),
						'dateBlockingIp' => LightMetaProperty::fill(new LightMetaProperty(), 'dateBlockingIp', 'date_blocking_ip', 'timestampTZ', 'TimestampTZ', null, false, true, false, null, null),
						'blackList' => LightMetaProperty::fill(new LightMetaProperty(), 'blackList', 'black_ip_list_id', 'identifier', 'PlatformUsersBlackIpList', null, false, false, false, 1, 3),
						'successful' => LightMetaProperty::fill(new LightMetaProperty(), 'successful', null, 'boolean', null, null, false, true, false, null, null),
						'whiteIpList' => LightMetaProperty::fill(new LightMetaProperty(), 'whiteIpList', 'white_ip_list_id', 'identifier', 'PlatformUsersWhiteIpList', null, false, false, false, 1, 3),
						'adminCode' => LightMetaProperty::fill(new LightMetaProperty(), 'adminCode', 'admin_code_id', 'identifier', 'PlatformUsersAdminCode', null, false, false, false, 1, 3)
					)
				);
		}
	}
?>