<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-10 14:23:47                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformBaseRequest extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				
			);
		}
	}
?>