<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-09 10:44:52                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformCommonNews extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PlatformCommonNews', 8, true, true, false, null, null),
				'project' => LightMetaProperty::fill(new LightMetaProperty(), 'project', 'project_id', 'identifier', 'PlatformCommonProject', null, true, false, false, 1, 3),
				'newsDraft' => LightMetaProperty::fill(new LightMetaProperty(), 'newsDraft', 'news_draft_id', 'identifier', 'PlatformCommonNewsDraft', null, false, false, false, 1, 3),
				'newsPublished' => LightMetaProperty::fill(new LightMetaProperty(), 'newsPublished', 'news_published_id', 'identifier', 'PlatformCommonNewsPublished', null, false, false, false, 1, 3),
				'createdAt' => LightMetaProperty::fill(new LightMetaProperty(), 'createdAt', 'created_at', 'timestampTZ', 'TimestampTZ', null, false, true, false, null, null),
				'publishedAt' => LightMetaProperty::fill(new LightMetaProperty(), 'publishedAt', 'published_at', 'timestampTZ', 'TimestampTZ', null, false, true, false, null, null),
				'published' => LightMetaProperty::fill(new LightMetaProperty(), 'published', null, 'boolean', null, null, false, true, false, null, null)
			);
		}
	}
?>