<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-23 14:04:39                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoModuleMultimediaResponse extends ProtoPlatformBaseResponse
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'string', null, null, false, true, false, null, null),
						'sourceFile' => LightMetaProperty::fill(new LightMetaProperty(), 'sourceFile', 'source_file', 'string', null, null, false, true, false, null, null),
						'preparedFile' => LightMetaProperty::fill(new LightMetaProperty(), 'preparedFile', 'prepared_file', 'string', null, null, false, true, false, null, null),
						'icoFile' => LightMetaProperty::fill(new LightMetaProperty(), 'icoFile', 'ico_file', 'string', null, null, false, true, false, null, null),
						'rootDirectory' => LightMetaProperty::fill(new LightMetaProperty(), 'rootDirectory', 'root_directory', 'string', null, 256, false, true, false, null, null),
						'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 32, false, true, false, null, null),
						'title' => LightMetaProperty::fill(new LightMetaProperty(), 'title', null, 'string', null, 32, false, true, false, null, null),
						'description' => LightMetaProperty::fill(new LightMetaProperty(), 'description', null, 'string', null, 256, false, true, false, null, null),
						'tags' => LightMetaProperty::fill(new LightMetaProperty(), 'tags', null, 'string', null, 512, false, true, false, null, null),
						'uploadedAt' => LightMetaProperty::fill(new LightMetaProperty(), 'uploadedAt', 'uploaded_at', 'timestampTZ', 'TimestampTZ', null, false, true, false, null, null),
						'mimeType' => LightMetaProperty::fill(new LightMetaProperty(), 'mimeType', 'mime_type', 'string', null, 128, false, true, false, null, null)
					)
				);
		}
	}
?>