<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-04-08 13:17:18                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoModuleMultimediaGetImageOperationResponse extends ProtoModuleMultimediaResponse
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'imagesSizes' => LightMetaProperty::fill(new LightMetaProperty(), 'imagesSizes', 'images_sizes', 'string', null, null, false, true, false, null, null),
						'imagesPreviewSizes' => LightMetaProperty::fill(new LightMetaProperty(), 'imagesPreviewSizes', 'images_preview_sizes_id', 'identifier', 'PlatformMultimediaImagesSize', null, false, false, false, 1, 3),
						'multimediaHost' => LightMetaProperty::fill(new LightMetaProperty(), 'multimediaHost', 'multimedia_host', 'string', null, null, false, true, false, null, null)
					)
				);
		}
	}
?>