<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-09 11:24:40                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformUsersModuleOperation extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PlatformUsersModuleOperation', 8, true, true, false, null, null),
				'module' => LightMetaProperty::fill(new LightMetaProperty(), 'module', 'module_id', 'identifier', 'PlatformCommonModule', null, true, false, false, 1, 3),
				'role' => LightMetaProperty::fill(new LightMetaProperty(), 'role', 'role_id', 'identifier', 'PlatformUsersRole', null, true, false, false, 1, 3),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 32, true, true, false, null, null)
			);
		}
	}
?>