<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-08 12:48:05                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformUsersAuthCommon extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PlatformUsersAuthCommon', 8, true, true, false, null, null),
				'userInfo' => LightMetaProperty::fill(new LightMetaProperty(), 'userInfo', 'user_info_id', 'identifier', 'PlatformUsersUserInfo', null, true, false, false, 1, 3),
				'authType' => LightMetaProperty::fill(new LightMetaProperty(), 'authType', 'auth_type_id', 'identifier', 'PlatformUsersAuthType', null, true, false, false, 1, 3),
				'token' => LightMetaProperty::fill(new LightMetaProperty(), 'token', null, 'string', null, 128, true, true, false, null, null),
				'refreshToken' => LightMetaProperty::fill(new LightMetaProperty(), 'refreshToken', 'refresh_token', 'string', null, 128, false, true, false, null, null),
				'profileUrl' => LightMetaProperty::fill(new LightMetaProperty(), 'profileUrl', 'profile_url', 'string', null, 128, true, true, false, null, null)
			);
		}
	}
?>