<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-08 10:13:57                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformUsersUserInfo extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PlatformUsersUserInfo', 8, true, true, false, null, null),
				'user' => LightMetaProperty::fill(new LightMetaProperty(), 'user', 'user_id', 'identifier', 'PlatformUsersUser', null, true, false, false, 1, 3),
				'lastName' => LightMetaProperty::fill(new LightMetaProperty(), 'lastName', 'last_name', 'string', null, 64, true, true, false, null, null),
				'firstName' => LightMetaProperty::fill(new LightMetaProperty(), 'firstName', 'first_name', 'string', null, 64, true, true, false, null, null),
				'middleName' => LightMetaProperty::fill(new LightMetaProperty(), 'middleName', 'middle_name', 'string', null, 64, true, true, false, null, null),
				'birthday' => LightMetaProperty::fill(new LightMetaProperty(), 'birthday', null, 'timestampTZ', 'TimestampTZ', null, true, true, false, null, null),
				'settings' => LightMetaProperty::fill(new LightMetaProperty(), 'settings', null, 'hstore', 'Hstore', null, true, true, false, null, null),
				'openId' => LightMetaProperty::fill(new LightMetaProperty(), 'openId', 'open_id', 'boolean', null, null, true, true, false, null, null),
				'registredAt' => LightMetaProperty::fill(new LightMetaProperty(), 'registredAt', 'registred_at', 'timestampTZ', 'TimestampTZ', null, true, true, false, null, null),
				'createdAt' => LightMetaProperty::fill(new LightMetaProperty(), 'createdAt', 'created_at', 'timestampTZ', 'TimestampTZ', null, true, true, false, null, null),
				'registred' => LightMetaProperty::fill(new LightMetaProperty(), 'registred', null, 'boolean', null, null, true, true, false, null, null),
				'lastLogin' => LightMetaProperty::fill(new LightMetaProperty(), 'lastLogin', 'last_login', 'timestampTZ', 'TimestampTZ', null, false, true, false, null, null),
				'signature' => LightMetaProperty::fill(new LightMetaProperty(), 'signature', null, 'string', null, 256, false, true, false, null, null),
				'preview' => LightMetaProperty::fill(new LightMetaProperty(), 'preview', null, 'boolean', null, null, true, true, false, null, null),
				'previewImageTypeId' => LightMetaProperty::fill(new LightMetaProperty(), 'previewImageTypeId', 'preview_image_type_id', 'string', null, null, true, true, false, null, null),
				'phone' => LightMetaProperty::fill(new LightMetaProperty(), 'phone', null, 'string', null, null, false, true, false, null, null)
			);
		}
	}
?>