<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-17 14:57:10                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoModuleRubricsSaveOperationRequest extends ProtoModuleRubricsRequest
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'parent' => LightMetaProperty::fill(new LightMetaProperty(), 'parent', null, 'string', null, null, false, true, false, null, null)
					)
				);
		}
	}
?>