<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-04-08 15:24:53                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoModuleMultimediaCropImageOperationRequest extends ProtoModuleMultimediaRequest
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integer', null, 4, false, true, false, null, null),
						'images' => LightMetaProperty::fill(new LightMetaProperty(), 'images', 'images_id', 'identifier', 'PlatformMultimediaImages', null, false, false, false, 1, 3),
						'imagesSize' => LightMetaProperty::fill(new LightMetaProperty(), 'imagesSize', 'images_size_id', 'identifier', 'PlatformMultimediaImagesSize', null, false, false, false, 1, 3),
						'path' => LightMetaProperty::fill(new LightMetaProperty(), 'path', null, 'string', null, null, false, true, false, null, null),
						'coordinateX' => LightMetaProperty::fill(new LightMetaProperty(), 'coordinateX', 'coordinate_x', 'float', null, 4, true, true, false, null, null),
						'coordinateY' => LightMetaProperty::fill(new LightMetaProperty(), 'coordinateY', 'coordinate_y', 'float', null, 4, true, true, false, null, null),
						'width' => LightMetaProperty::fill(new LightMetaProperty(), 'width', null, 'float', null, 4, true, true, false, null, null),
						'height' => LightMetaProperty::fill(new LightMetaProperty(), 'height', null, 'float', null, 4, true, true, false, null, null),
						'croppedAt' => LightMetaProperty::fill(new LightMetaProperty(), 'croppedAt', 'cropped_at', 'timestampTZ', 'TimestampTZ', null, false, true, false, null, null)
					)
				);
		}
	}
?>