<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-11 09:20:59                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoVkResponse extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'method' => LightMetaProperty::fill(new LightMetaProperty(), 'method', null, 'string', null, null, true, true, false, null, null),
				'postId' => LightMetaProperty::fill(new LightMetaProperty(), 'postId', 'post_id', 'string', null, null, false, true, false, null, null)
			);
		}
	}
?>