<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-24 10:23:21                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformUsersAdminCode extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PlatformUsersAdminCode', 8, true, true, false, null, null),
				'code' => LightMetaProperty::fill(new LightMetaProperty(), 'code', null, 'string', null, 32, true, true, false, null, null),
				'createdAt' => LightMetaProperty::fill(new LightMetaProperty(), 'createdAt', 'created_at', 'timestampTZ', 'TimestampTZ', null, true, true, false, null, null),
				'active' => LightMetaProperty::fill(new LightMetaProperty(), 'active', null, 'boolean', null, null, false, true, false, null, null),
				'type' => LightMetaProperty::fill(new LightMetaProperty(), 'type', 'type_id', 'enum', 'PlatformUsersAdminCodeTypeEnum', null, true, false, false, 1, 3),
				'admin' => LightMetaProperty::fill(new LightMetaProperty(), 'admin', 'user_id', 'identifier', 'PlatformUsersAdmin', null, true, false, false, 1, 3)
			);
		}
	}
?>