<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-13 12:13:25                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformPublisherApplication extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PlatformPublisherApplication', 8, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 32, true, true, false, null, null),
				'socialNetwork' => LightMetaProperty::fill(new LightMetaProperty(), 'socialNetwork', 'social_network', 'integer', null, 4, true, true, false, null, null),
				'appId' => LightMetaProperty::fill(new LightMetaProperty(), 'appId', 'app_id', 'integer', null, 4, true, true, false, null, null),
				'appSecretKey' => LightMetaProperty::fill(new LightMetaProperty(), 'appSecretKey', 'app_secret_key', 'string', null, null, true, true, false, null, null)
			);
		}
	}
?>