<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-27 11:18:06                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformSocialFlowGroups extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PlatformSocialFlowGroups', 8, true, true, false, null, null),
				'flow' => LightMetaProperty::fill(new LightMetaProperty(), 'flow', 'flow_id', 'identifier', 'PlatformSocialFlow', null, true, false, false, 1, 3),
				'group' => LightMetaProperty::fill(new LightMetaProperty(), 'group', 'group_id', 'identifier', 'PlatformSocialAppAdminGroup', null, true, false, false, 1, 3)
			);
		}
	}
?>