<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-17 13:14:01                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoModuleMultimediaAddImageOperationRequest extends ProtoModuleMultimediaRequest
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'images' => LightMetaProperty::fill(new LightMetaProperty(), 'images', null, 'string', null, null, false, true, false, null, null)
					)
				);
		}
	}
?>