<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-23 10:27:54                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoModuleMultimediaGetImageOperationRequest extends ProtoModuleMultimediaRequest
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'sizesId' => LightMetaProperty::fill(new LightMetaProperty(), 'sizesId', 'sizes_id', 'integer', null, 4, false, true, false, null, null)
					)
				);
		}
	}
?>