<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-13 09:36:08                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoModuleRubricsGetAllListOperationResponse extends ProtoModuleRubricsRequest
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'data' => LightMetaProperty::fill(new LightMetaProperty(), 'data', null, 'string', null, null, false, true, false, null, null)
					)
				);
		}
	}
?>