<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-26 14:07:20                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformBaseResponse extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				
			);
		}
	}
?>