<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-23 11:20:04                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformSmsRequest extends ProtoPlatformBaseRequest
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'phone' => LightMetaProperty::fill(new LightMetaProperty(), 'phone', null, 'string', null, 17, true, true, false, null, null),
						'message' => LightMetaProperty::fill(new LightMetaProperty(), 'message', null, 'string', null, 256, true, true, false, null, null)
					)
				);
		}
	}
?>