<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-27 11:28:58                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformCommonRubric extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PlatformCommonRubric', 8, true, true, false, null, null),
				'project' => LightMetaProperty::fill(new LightMetaProperty(), 'project', 'project_id', 'identifier', 'PlatformCommonProject', null, false, false, false, 1, 3),
				'rubricData' => LightMetaProperty::fill(new LightMetaProperty(), 'rubricData', 'rubric_data_id', 'identifier', 'PlatformCommonRubricData', null, false, false, false, 1, 3),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, null, true, true, false, null, null),
				'path' => LightMetaProperty::fill(new LightMetaProperty(), 'path', null, 'string', null, null, true, true, false, null, null),
				'enabled' => LightMetaProperty::fill(new LightMetaProperty(), 'enabled', null, 'boolean', null, null, true, true, false, null, null),
				'createdAt' => LightMetaProperty::fill(new LightMetaProperty(), 'createdAt', 'created_at', 'timestampTZ', 'TimestampTZ', null, false, true, false, null, null),
				'modifiedAt' => LightMetaProperty::fill(new LightMetaProperty(), 'modifiedAt', 'modified_at', 'timestampTZ', 'TimestampTZ', null, false, true, false, null, null)
			);
		}
	}
?>