<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-23 12:25:38                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformSendCodeRequest extends ProtoPlatformBaseRequest
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'code' => LightMetaProperty::fill(new LightMetaProperty(), 'code', null, 'string', null, 5, true, true, false, null, null),
						'type' => LightMetaProperty::fill(new LightMetaProperty(), 'type', 'type_id', 'enum', 'PlatformUsersAdminCodeTypeEnum', null, true, false, false, 1, 3)
					)
				);
		}
	}
?>