<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-12 11:36:30                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformUsersBlackIpList extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PlatformUsersBlackIpList', 8, true, true, false, null, null),
				'ipAddress' => LightMetaProperty::fill(new LightMetaProperty(), 'ipAddress', 'ip_address', 'string', null, 15, true, true, false, null, null),
				'expires' => LightMetaProperty::fill(new LightMetaProperty(), 'expires', null, 'timestampTZ', 'TimestampTZ', null, false, true, false, null, null),
				'active' => LightMetaProperty::fill(new LightMetaProperty(), 'active', null, 'boolean', null, null, false, true, false, null, null)
			);
		}
	}
?>