<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-17 13:31:11                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoModuleMultimediaSearchOperationResponse extends ProtoModuleMultimediaResponse
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'draw' => LightMetaProperty::fill(new LightMetaProperty(), 'draw', null, 'integer', null, 4, false, true, false, null, null),
						'recordsTotal' => LightMetaProperty::fill(new LightMetaProperty(), 'recordsTotal', 'records_total', 'integer', null, 4, false, true, false, null, null),
						'recordsFiltered' => LightMetaProperty::fill(new LightMetaProperty(), 'recordsFiltered', 'records_filtered', 'integer', null, 4, false, true, false, null, null),
						'data' => LightMetaProperty::fill(new LightMetaProperty(), 'data', null, 'string', null, null, false, true, false, null, null)
					)
				);
		}
	}
?>