<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-16 14:35:19                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoModuleMultimediaAddImageOperationResponse extends ProtoModuleMultimediaResponse
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'IcoPath' => LightMetaProperty::fill(new LightMetaProperty(), 'IcoPath', '_ico_path', 'string', null, null, false, true, false, null, null)
					)
				);
		}
	}
?>