<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-22 08:14:00                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformUsersAdmin extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PlatformUsersAdmin', 8, true, true, false, null, null),
				'login' => LightMetaProperty::fill(new LightMetaProperty(), 'login', null, 'string', null, 32, true, true, false, null, null),
				'password' => LightMetaProperty::fill(new LightMetaProperty(), 'password', null, 'string', null, 256, true, true, false, null, null),
				'email' => LightMetaProperty::fill(new LightMetaProperty(), 'email', null, 'string', null, 32, false, true, false, null, null),
				'phone' => LightMetaProperty::fill(new LightMetaProperty(), 'phone', null, 'string', null, 16, true, true, false, null, null),
				'xmppAccount' => LightMetaProperty::fill(new LightMetaProperty(), 'xmppAccount', 'xmpp_account', 'string', null, 40, false, true, false, null, null),
				'blocked' => LightMetaProperty::fill(new LightMetaProperty(), 'blocked', null, 'boolean', null, null, false, true, false, null, null)
			);
		}
	}
?>