<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-09 11:24:40                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformUsersAdminRole extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'PlatformUsersAdminRole', 8, true, true, false, null, null),
				'admin' => LightMetaProperty::fill(new LightMetaProperty(), 'admin', 'admin_id', 'identifier', 'PlatformUsersAdmin', null, true, false, false, 1, 3),
				'role' => LightMetaProperty::fill(new LightMetaProperty(), 'role', 'role_id', 'identifier', 'PlatformUsersRole', null, true, false, false, 1, 3)
			);
		}
	}
?>