<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-11 13:06:50                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPlatformAuthAdminResponse extends ProtoPlatformBaseResponse
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'result' => LightMetaProperty::fill(new LightMetaProperty(), 'result', null, 'boolean', null, null, true, true, false, null, null)
					)
				);
		}
	}
?>