<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-16 08:51:34                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformMultimediaCroppedImagesDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'multimedia.cropped_images';
		}
		
		public function getObjectName()
		{
			return 'PlatformMultimediaCroppedImages';
		}
		
		public function getSequence()
		{
			return 'multimedia.cropped_images_id';
		}
	}
?>