<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-27 11:18:06                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformSocialFlowPagesDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'social.flow_dimension_page';
		}
		
		public function getObjectName()
		{
			return 'PlatformSocialFlowPages';
		}
		
		public function getSequence()
		{
			return 'social.flow_dimension_page_id';
		}
	}
?>