<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-09 11:45:16                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformUsersRoleDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'users.role';
		}
		
		public function getObjectName()
		{
			return 'PlatformUsersRole';
		}
		
		public function getSequence()
		{
			return 'users.role_id';
		}
	}
?>