<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-12 11:36:30                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformUsersBlackIpListDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'users.black_ip_list';
		}
		
		public function getObjectName()
		{
			return 'PlatformUsersBlackIpList';
		}
		
		public function getSequence()
		{
			return 'users.black_ip_list_id';
		}
	}
?>