<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-06-14 08:57:03                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoMultimediaUnsortedDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'multimedia.unsorted';
		}
		
		public function getObjectName()
		{
			return 'MultimediaUnsorted';
		}
		
		public function getSequence()
		{
			return 'multimedia.unsorted_id';
		}
	}
?>