<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-22 08:15:04                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformUsersAdminProfileDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'users.admin_profile';
		}
		
		public function getObjectName()
		{
			return 'PlatformUsersAdminProfile';
		}
		
		public function getSequence()
		{
			return 'users.admin_profile_id';
		}
	}
?>