<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-22 08:28:40                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformUsersWhiteIpListDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'users.white_ip_list';
		}
		
		public function getObjectName()
		{
			return 'PlatformUsersWhiteIpList';
		}
		
		public function getSequence()
		{
			return 'users.white_ip_list_id';
		}
	}
?>