<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-13 12:13:25                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformPublisherApplicationDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'publisher.application';
		}
		
		public function getObjectName()
		{
			return 'PlatformPublisherApplication';
		}
		
		public function getSequence()
		{
			return 'publisher.application_id';
		}
	}
?>