<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-08 11:57:41                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformUsersAuthTypeDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'users.auth_type';
		}
		
		public function getObjectName()
		{
			return 'PlatformUsersAuthType';
		}
		
		public function getSequence()
		{
			return 'users.auth_type_id';
		}
	}
?>