<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-15 10:16:42                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformCommonRubricDataDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'common.rubric_data';
		}
		
		public function getObjectName()
		{
			return 'PlatformCommonRubricData';
		}
		
		public function getSequence()
		{
			return 'common.rubric_data_id';
		}
	}
?>