<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-15 10:44:49                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformCommonRubricDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'common.rubric';
		}
		
		public function getObjectName()
		{
			return 'PlatformCommonRubric';
		}
		
		public function getSequence()
		{
			return 'common.rubric_id';
		}
	}
?>