<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-09 14:03:27                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformUsersAdminInfoDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'users.admin_info';
		}
		
		public function getObjectName()
		{
			return 'PlatformUsersAdminInfo';
		}
		
		public function getSequence()
		{
			return 'users.admin_info_id';
		}
	}
?>