<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-04-11 09:08:09                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformSocialPublishedLinkDataDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'social.published_data';
		}
		
		public function getObjectName()
		{
			return 'PlatformSocialPublishedLinkData';
		}
		
		public function getSequence()
		{
			return 'social.published_data_id';
		}
	}
?>