<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-14 14:07:19                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformSocialAppAdminDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'social.app_admin';
		}
		
		public function getObjectName()
		{
			return 'PlatformSocialAppAdmin';
		}
		
		public function getSequence()
		{
			return 'social.app_admin_id';
		}
	}
?>