<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-20 11:37:42                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformMultimediaImagesSizeDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'multimedia.images_size';
		}
		
		public function getObjectName()
		{
			return 'PlatformMultimediaImagesSize';
		}
		
		public function getSequence()
		{
			return 'multimedia.images_size_id';
		}
	}
?>