<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-26 12:46:59                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformCommonArticleDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'common.article';
		}
		
		public function getObjectName()
		{
			return 'PlatformCommonArticle';
		}
		
		public function getSequence()
		{
			return 'common.article_id';
		}
	}
?>