<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-04-13 14:17:57                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoModuleArticleAutoSaveOperationResponse extends AutoProtoModuleArticleAutoSaveOperationResponse {/*_*/}
?>