<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-11 09:20:59                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoVkResponse extends AutoProtoVkResponse {/*_*/}
?>