<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-27 09:47:05                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoModuleMultimediaGetPreviewListResponse extends AutoProtoModuleMultimediaGetPreviewListResponse {/*_*/}
?>