<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-09 11:24:40                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoPlatformUsersModuleOperation extends AutoProtoPlatformUsersModuleOperation {/*_*/}
?>