<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-12 14:33:36                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoPlatformLogsAdminAuthLogsRequest extends AutoProtoPlatformLogsAdminAuthLogsRequest {/*_*/}
?>