<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-29 09:05:13                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoModuleArticleSearchOperationResponse extends AutoProtoModuleArticleSearchOperationResponse {/*_*/}
?>