<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-24 08:58:28                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoModuleMultimediaCropImageOperationRequest extends AutoProtoModuleMultimediaCropImageOperationRequest {/*_*/}
?>