<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-22 08:28:40                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoPlatformUsersWhiteIpList extends AutoProtoPlatformUsersWhiteIpList {/*_*/}
?>