<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-13 08:34:53                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoModuleRubricsGetAllListOperationResponse extends AutoProtoModuleRubricsGetAllListOperationResponse {/*_*/}
?>