<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-26 12:46:59                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoPlatformCommonArticle extends AutoProtoPlatformCommonArticle {/*_*/}
?>