<?php
/**
 * dewid
 * Created by PhpStorm.
 * User: user
 * Date: 03.12.14
 * Time: 15:25
 */

define('ENVIRONMENT_PROJECT', 'Development');

//define('ENVIRONMENT_PROJECT', 'Testing');
//define('ENVIRONMENT_PROJECT', 'Production');


define('PATH_PROJECT_BASE', dirname(__FILE__) . DIRECTORY_SEPARATOR);
define('PATH_PROJECT', PATH_PROJECT_BASE);
define('PATH_PROJECT_SRC', PATH_PROJECT . 'src' . DIRECTORY_SEPARATOR);
define('PATH_PROJECT_TEMPLATES', PATH_PROJECT_SRC . 'templates' . DIRECTORY_SEPARATOR);
define('PATH_PROJECT_CLASSES', PATH_PROJECT_SRC . 'classes' . DIRECTORY_SEPARATOR);
define('PATH_PROJECT_CONTROLLERS', PATH_PROJECT_CLASSES . 'Controllers' . DIRECTORY_SEPARATOR);
define('PATH_PROJECT_API', PATH_PROJECT_CLASSES . 'Api' . DIRECTORY_SEPARATOR);
define('PATH_PROJECT_UTILS', PATH_PROJECT_CLASSES . 'Utils' . DIRECTORY_SEPARATOR);
define('PATH_PROJECT_HELPERS', PATH_PROJECT_CLASSES . 'Helpers' . DIRECTORY_SEPARATOR);

define('PATH_PROJECT_CLASSES_BASE', PATH_PROJECT_CLASSES . 'Base' . DIRECTORY_SEPARATOR);

define('PATH_INDEX', PATH_PROJECT . '../web' . DIRECTORY_SEPARATOR);
define('PATH_PROJECT_FONT', PATH_PROJECT . 'font' . DIRECTORY_SEPARATOR);
define('PATH_PROJECT_CONFIG', PATH_PROJECT . 'config' . DIRECTORY_SEPARATOR);

define('PATH_PROJECT_WEB', '//multimedia.pravda.ru/');
define('COOKIE_HOST_NAME', 'project');
define('SESSION_HOST_NAME', 'project');
