/**
 * Created by root on 18.02.15.
 */
$.fn.technomedia = {
    totalError: ['Ошибка на сайте обратитесь к разработчикам'],
    saveRubricOk: ['Рубрика успешно сохраннена'],
    errorRubricTitle: ['Ошибка'],
    selectedRubric: ['Выберите рубрику'],
    saveRubricDialogMessage: ['Cохранить  рубрику?'],
    updateRubricDialogMessage: ['Будут переименованны подрубрики. Сохранить рубрику'],
    insertDataForm:['Пожалуйста заполните поле `Название`'],
    btnSaveOk:['<i class="fa fa-save fa-fw"></i>Сохранить'],
    btnRemoveOk: ['<i class="fa fa-trash-o fa-fw"></i>Удалить'],
    btnSaveCancel:['Отмена'],
    btnErrorCancel:['Закрыть'],
    btnClose:['Закрыть'],
    saveArticleDialog:['Сохранить статью?'],
    addArticlesMessageOk:['Статья успешно сохраненна'],
    addArticlesMessageOkBtnList:['Список статей'],
    addArticlesMessageOkBtnNew:['Новая статья'],
    saveNewsDialog:['Сохранить новость?'],
    addNewsMessageOk:['Новость успешно сохраненна'],
    addNewsMessageOkBtnList:['Список новостей'],
    addNewsMessageOkBtnNew:['Новая `Новость`'],
    selectedRubricErrorMax:['Превышенно количество рубрик! Материал можно максимально привязать к трем рубрикам'],
    noSelectedRubricError:['Вы не выбрали рубрики!'],
    treeRubricsName:['Дерево рубрик'],
    addRubricMessageOkBtnList:['Список рубрик'],
    addRubricMessageOkBtnNew:['Новая `Рубрика`'],
    addRubricMessageOk:['Рубрика успешно сохраненна'],
    addCropImagesMessage:['Вы действительно хотите, сохранить выделенную область изображения?'],
    saveCropImagesOkMessage:['Изображение успешно сохраненно'],
    addAppMessage:['Вы действительно хотите добавить это приложение'],
    btnNext: ['Продолжить'],
    btnList: ['Список'],
    width: ['Ширина'],
    height: ['Высота'],
    appAddError: ['Ошибка при создании приложения обратитесь к разработчикам, или проверте все параметры'],
    appAddSuccess: ['Вы успешно добавили приложение следущим шагом не обходимо добавить Администратора'],
    appAddGroupSuccess: ['Вы успешно добавили группу'],
    addDialogGroupMessage: ['Вы действительно хотите сохранить группу'],
    appAddPageSuccess: ['Вы успешно добавили страниц'],
    addDialogPageMessage: ['Вы действительно хотите сохранить страницу'],
    appType: ['Тип приложения'],
    additionally: ['Дополнительно'],
    additionallyAddAdminName: ['Имя администратора'],
    additionallyAddAccessToken: ['Ключ доступа к приложению (access token)'],
    additionallySocialAdminId: ['ID пользователя в соц. сети'],
    addStandaloneApp: ['Вы успешно добавить приложение пожалуйста добавьте группы'],
    addUserAppMessage: ['Пройдите авторизацию'],
    addUserAppAccessTokenMessage: ['Пройдите авторизацию и скопируйте access-token из URL'],
    addAppIdRequired: ['Полe ID приложения обязательно для заполнения'],
    deleteAppConfirmMessage: ['Вы действительно хотите удалить приложение '],
    addFlowError: ['Вы не добавили не одной ГРУППЫ и не одной СТРАНИЦЫ'],
    addFlowOk: ['Вы успешно сохранили новый поток'],
    saveFlowOk: ['Вы успешно сохранили поток '],
    deleteFlowConfirmMessage: ['Вы действительно хотите удалить поток']
};