<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-06-14 08:57:03                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class MultimediaUnsortedDAO extends AutoMultimediaUnsortedDAO
	{
		// your brilliant stuff goes here
	}
?>