<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-09 09:45:08                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformUsersAdminDAO extends AutoPlatformUsersAdminDAO
	{
        /**
         * Получить по $id
         *
         * @param $id
         * @param int $expires
         * @return  PlatformUsersAdmin
         */
        public function getById($id, $expires = Cache::EXPIRES_MEDIUM)
        {
            return parent::getById($id, $expires);
        }

        /**
         * @return string
         */
        public function getSequence()
        {
            return parent::getSequence() . '_seq';
        }

        /**
         * Получить по $login
         *
         * @param $login
         * @return PlatformUsersAdmin
         */
        public function getByLogin($login)
        {
            return Criteria::create($this)
                ->setSilent(FALSE)
                ->add(
                    Expression::eq(
                        DBField::create('login'),
                        DBValue::create($login)
                    )
                )
                ->get();
        }
	}
?>