<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-22 08:14:02                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformUsersAdminCodeDAO extends AutoPlatformUsersAdminCodeDAO
	{
		// your brilliant stuff goes here
        public function getSequence()
        {
            return parent::getSequence().'_seq';
        }

        /**
         * Получить по айди пользователя uid и коду по умолчанию активного кода
         *
         * @param $uId
         * @param $code
         * @param bool $active
         * @return PlatformUsersAdminCode
         */
        public function getCodeByUidAndCodeAndActive($uId, $code, $active = TRUE)
        {
            return Criteria::create($this)
                ->setSilent(FALSE)
                ->add(
                    Expression::eq(
                        DBField::create('user_id'),
                        DBValue::create($uId)
                    )
                )
                ->add(
                    Expression::eq(
                        DBField::create('code'),
                        DBValue::create($code)
                    )
                )
                ->add(
                    Expression::eq(
                        DBField::create('active'),
                        DBValue::create($active)
                    )
                )
                ->get()
                ;
        }
	}
?>