<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-26 12:46:59                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformCommonArticleDraftDAO extends AutoPlatformCommonArticleDraftDAO
	{
		// your brilliant stuff goes here
        /**
         * Получить черновик статьи по айди
         *
         * @param $id
         * @param int $expires
         * @return  PlatformCommonArticleDraft
         */
        public function getById($id, $expires = Cache::EXPIRES_MEDIUM)
        {
            return parent::getById($id, $expires);
        }

        /**
         * Сиквенц
         *
         * @return string
         */
        public function getSequence()
        {
            return parent::getSequence() . '_seq';
        }
	}
?>