<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-08 10:10:45                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformUsersUserDAO extends AutoPlatformUsersUserDAO
	{
        /**
         * @param $id
         * @param int $expires
         * @return PlatformUsersUser
         */
        public function getById($id, $expires = Cache::EXPIRES_MEDIUM)
        {
            return parent::getById($id, $expires);
        }

        /**
         * @return string
         */
        public function getSequence()
        {
            return parent::getSequence() . '_seq';
        }

        /**
         * @param $email
         * @return PlatformUsersUser
         */
        public function getByEmail($email)
        {
            return Criteria::create($this)
                ->setSilent(FALSE)
                ->add(
                    Expression::eq(
                        DBField::create('email'),
                        DBValue::create($email)
                    )
                )
                ->get();
        }
	}
?>