<?php

/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-14 14:07:19                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
class PlatformSocialAppAdminGroupDAO extends AutoPlatformSocialAppAdminGroupDAO
{
    // your brilliant stuff goes here
    /**
     * @return string
     */
    public function getSequence()
    {
        return parent::getSequence() . '_seq'; // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @param int $expires
     * @return PlatformSocialAppAdminGroup
     */
    public function getById($id, $expires = Cache::EXPIRES_MEDIUM)
    {
        return parent::getById($id, $expires); // TODO: Change the autogenerated stub
    }

    /**
     * @param PlatformSocialAppAdmin $admin
     * @return  PlatformSocialAppAdminGroup[]
     * @throws ObjectNotFoundException
     */
    public function getListByAdmin(PlatformSocialAppAdmin $admin)
    {
        return (new Criteria($this))
            ->setSilent(false)
            ->add(Expression::eq('appAdmin', $admin))
            ->getList();
    }

    /**
     * @param PlatformSocialAppAdmin $admin
     * @param $id
     * @return PlatformSocialAppAdminGroup
     * @throws ObjectNotFoundException
     */
    public function getByAdminAndSocialId(PlatformSocialAppAdmin $admin, $id)
    {
        return (new Criteria($this))
            ->setSilent(false)
            ->add(Expression::eq('appAdmin', $admin))
            ->add(Expression::eq('groupId', $id))
            ->get();
    }

    /**
     * @param $appId
     * @param array $notIn
     * @return array
     * @throws ObjectNotFoundException
     */
    public function getByAppId($appId, array $notIn)
    {
        $criteria = (new Criteria($this))
            ->setSilent(true)
            ->add(Expression::eq('appAdmin.app', $appId));

        if (!empty($notIn))
            $criteria->add(Expression::notIn('id', $notIn));

        return $criteria->getCustomList();
    }

}

?>