<?php

/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-12 14:13:09                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
class PlatformLogsAdminAuthLogsDAO extends AutoPlatformLogsAdminAuthLogsDAO
{
    /**
     * @return string
     */
    public function getSequence()
    {
        return parent::getSequence() . '_seq';
    }


    /**
     * Получение по $ip и обьекту TimestampTZ
     *
     * @param $ip
     * @param TimestampTZ $time
     * @return null
     */
    public function getCountByIpAndTime($ip, TimestampTZ $time)
    {
        return Criteria::create($this)
            ->setSilent(FALSE)
            ->addProjection(
                Projection::chain()
                    ->add(Projection::count('id', 'count'))
            )
            ->add(
                Expression::gt(
                    DBField::create('entry_at'),
                    DBValue::create($time->toIsoString())
                )
            )
            ->add(
                Expression::eq(
                    DBField::create('ip'),
                    DBValue::create($ip)
                )
            )
            ->getCustom('count');
    }
}

?>