<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-09 11:24:40                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformUsersModuleOperationDAO extends AutoPlatformUsersModuleOperationDAO
	{
        /**
         * @param $id
         * @param int $expires
         * @return  PlatformUsersModuleOperation
         */
        public function getById($id, $expires = Cache::EXPIRES_MEDIUM)
        {
            return parent::getById($id, $expires);
        }

        /**
         * @return string
         */
        public function getSequence()
        {
            return parent::getSequence() . '_seq';
        }

        public function getByRoleId($id)
        {
            $c = Criteria::create($this)
                ->setSilent(TRUE)
                ->add(
                    Expression::eq(
                        DBField::create('role_id'),
                        DBValue::create($id)
                    )
                )
                ->getList();

            return $c;
        }
	}
?>