<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-14 14:07:19                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformSocialAppAdminDAO extends AutoPlatformSocialAppAdminDAO
	{
		// your brilliant stuff goes here
		public function getSequence()
		{
			return parent::getSequence().'_seq'; // TODO: Change the autogenerated stub
		}

		/**
		 * @param $id
		 * @param int $expires
		 * @return PlatformSocialAppAdmin
		 */
		public function getById($id, $expires = Cache::EXPIRES_MEDIUM)
		{
			return parent::getById($id, $expires); // TODO: Change the autogenerated stub
		}

		/**
		 * PlatformSocialAppAdmin
		 * @param PlatformSocialApp $app
		 * @return mixed|null
		 * @throws ObjectNotFoundException
		 */
		public function getByApp(PlatformSocialApp $app)
		{
			return (new Criteria($this))
				->setSilent(false)
				->add(Expression::eq('app', $app))
				->get();
		}


	}
?>