<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-16 08:51:34                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformMultimediaCroppedImagesDAO extends AutoPlatformMultimediaCroppedImagesDAO
	{
		/**
		 * @return string
		 */
		public function getSequence()
		{
			return parent::getSequence() . '_seq';
		}

		/**
		 * Получение по $id
		 *
		 * @param $id
		 * @param int $expires
		 * @return  PlatformMultimediaCroppedImages
		 */
		public function getById($id, $expires = Cache::EXPIRES_MEDIUM)
		{
			return parent::getById($id, $expires);
		}


		/**
		 * @param PlatformMultimediaImages $images
		 * @return array
		 */
		public function getByImages(PlatformMultimediaImages $images)
		{
			return Criteria::create($this)
				->add(Expression::eq('images',$images))
				->getList();
		}
		// your brilliant stuff goes here
	}
?>