<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-08 13:10:19                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformCommonProjectDAO extends AutoPlatformCommonProjectDAO
	{
        /**
         * Полчение проекта по id
         *
         * @param $id
         * @param int $expires
         * @return PlatformCommonProject
         */
        public function getById($id, $expires = Cache::EXPIRES_MEDIUM)
        {
            return parent::getById($id, $expires);
        }

        /**
         * @param $nameProject
         * @return PlatformCommonProject
         */
        public function getByName($nameProject)
        {
            return Criteria::create($this)
                ->add(Expression::eq('name',$nameProject))
                ->get();
        }

        /**
         * @return string
         */
        public function getSequence()
        {
            return parent::getSequence() . '_seq';
        }
	}
?>