<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-20 13:51:46                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleMultimediaGetImageOperationResponse extends AutoModuleMultimediaGetImageOperationResponse implements Prototyped
	{
		/**
		 * @return ModuleMultimediaGetImageOperationResponse
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleMultimediaGetImageOperationResponse
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleMultimediaGetImageOperationResponse');
		}
		
		// your brilliant stuff goes here
	}
?>