<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-16 09:45:57                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleRubricsSearchOperationRequest extends AutoModuleRubricsSearchOperationRequest implements Prototyped
	{
		/**
		 * @return ModuleRubricsSearchOperationRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleRubricsSearchOperationRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleRubricsSearchOperationRequest');
		}
		
		// your brilliant stuff goes here
	}
?>