<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-11 11:20:41                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleMultimediaAddImageOperationResponse extends AutoModuleMultimediaAddImageOperationResponse implements Prototyped
	{
		/**
		 * @return ModuleMultimediaAddImageOperationResponse
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleMultimediaAddImageOperationResponse
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleMultimediaAddImageOperationResponse');
		}
		
		// your brilliant stuff goes here
	}
?>