<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-26 15:09:04                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleArticleRequest extends AutoModuleArticleRequest implements Prototyped
	{
		/**
		 * @return ModuleArticleRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleArticleRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleArticleRequest');
		}
		
		// your brilliant stuff goes here
	}
?>