<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-12 16:31:04                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleRubricsDropOperationResponse extends AutoModuleRubricsDropOperationResponse implements Prototyped
	{
		/**
		 * @return ModuleRubricsDropOperationResponse
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleRubricsDropOperationResponse
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleRubricsDropOperationResponse');
		}
		
		// your brilliant stuff goes here
	}
?>