<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-27 12:20:19                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleArticleDropOperationRequest extends AutoModuleArticleDropOperationRequest implements Prototyped
	{
		/**
		 * @return ModuleArticleDropOperationRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleArticleDropOperationRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleArticleDropOperationRequest');
		}
		
		// your brilliant stuff goes here
	}
?>