<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-27 12:08:45                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleArticleResponse extends AutoModuleArticleResponse implements Prototyped
	{
		/**
		 * @return ModuleArticleResponse
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleArticleResponse
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleArticleResponse');
		}
		
		// your brilliant stuff goes here
	}
?>