<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-12 16:21:58                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleRubricsAddOperationRequest extends AutoModuleRubricsAddOperationRequest implements Prototyped
	{
		/**
		 * @return ModuleRubricsAddOperationRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleRubricsAddOperationRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleRubricsAddOperationRequest');
		}
		
		// your brilliant stuff goes here
	}
?>