<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-27 09:47:05                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleMultimediaGetPreviewListResponse extends AutoModuleMultimediaGetPreviewListResponse implements Prototyped
	{
		/**
		 * @return ModuleMultimediaGetPreviewListResponse
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleMultimediaGetPreviewListResponse
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleMultimediaGetPreviewListResponse');
		}
		
		// your brilliant stuff goes here
	}
?>