<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-09 10:42:04                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleNewsGetOperationRequest extends AutoModuleNewsGetOperationRequest implements Prototyped
	{
		/**
		 * @return ModuleNewsGetOperationRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleNewsGetOperationRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleNewsGetOperationRequest');
		}
		
		// your brilliant stuff goes here
	}
?>