<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-27 09:48:55                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleArticleAddOperationResponse extends AutoModuleArticleAddOperationResponse implements Prototyped
	{
		/**
		 * @return ModuleArticleAddOperationResponse
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleArticleAddOperationResponse
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleArticleAddOperationResponse');
		}
		
		// your brilliant stuff goes here
	}
?>