<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-12 16:21:58                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleRubricsSaveOperationRequest extends AutoModuleRubricsSaveOperationRequest implements Prototyped
	{
		/**
		 * @return ModuleRubricsSaveOperationRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleRubricsSaveOperationRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleRubricsSaveOperationRequest');
		}
		
		// your brilliant stuff goes here
	}
?>