<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-04-13 14:17:57                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleArticleAutoSaveOperationResponse extends AutoModuleArticleAutoSaveOperationResponse implements Prototyped
	{
		/**
		 * @return ModuleArticleAutoSaveOperationResponse
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleArticleAutoSaveOperationResponse
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleArticleAutoSaveOperationResponse');
		}
		
		// your brilliant stuff goes here
	}
?>