<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-27 12:20:19                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleArticleGetOperationRequest extends AutoModuleArticleGetOperationRequest implements Prototyped
	{
		/**
		 * @return ModuleArticleGetOperationRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleArticleGetOperationRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleArticleGetOperationRequest');
		}
		
		// your brilliant stuff goes here
	}
?>