<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-20 13:51:46                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleMultimediaGetImageOperationRequest extends AutoModuleMultimediaGetImageOperationRequest implements Prototyped
	{
		/**
		 * @return ModuleMultimediaGetImageOperationRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleMultimediaGetImageOperationRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleMultimediaGetImageOperationRequest');
		}
		
		// your brilliant stuff goes here
	}
?>