<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-24 08:58:28                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ModuleMultimediaCropImageOperationRequest extends AutoModuleMultimediaCropImageOperationRequest implements Prototyped
	{
		/**
		 * @return ModuleMultimediaCropImageOperationRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoModuleMultimediaCropImageOperationRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoModuleMultimediaCropImageOperationRequest');
		}
		
		// your brilliant stuff goes here
	}
?>