<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-10 14:40:51                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformAuthAdminRequest extends AutoPlatformAuthAdminRequest implements Prototyped
	{
		/**
		 * @return PlatformAuthAdminRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoPlatformAuthAdminRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformAuthAdminRequest');
		}
		
		// your brilliant stuff goes here
	}
?>