<?php

/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-22 08:14:02                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
class PlatformUsersAdminCode extends AutoPlatformUsersAdminCode implements Prototyped, DAOConnected
{
    /**
     * @return PlatformUsersAdminCode
     **/
    public static function create()
    {
        return new self;
    }

    /**
     * @return PlatformUsersAdminCodeDAO
     **/
    public static function dao()
    {
        return Singleton::getInstance('PlatformUsersAdminCodeDAO');
    }

    /**
     * @return ProtoPlatformUsersAdminCode
     **/
    public static function proto()
    {
        return Singleton::getInstance('ProtoPlatformUsersAdminCode');
    }


    public static function addCode(PlatformAdminCodeRequest $request)
    {
        try {
            self::dao()->add(
                self::create()
                    ->setCode($request->getCode())
                    ->setType($request->getType())
                    ->setActive($request->getActive())
                    ->setCreatedAt($request->getCreatedAt())
                    ->setAdminId($request->getAdminId())
            );
        } catch (BaseException $e) {
            /**  */
        }
    }

    public static function checkCode($code, $uId)
    {
        try{
            $code = self::dao()->getCodeByUidAndCodeAndActive($uId, $code);

            self::dao()->save(
                $code->setActive(FALSE)
            );

            return TRUE;
        }catch (ObjectNotFoundException $e)
        {
            return FALSE;
        }
    }

    // your brilliant stuff goes here
}

?>