<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-08 13:25:11                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformUsersUserRegistrationFacts extends AutoPlatformUsersUserRegistrationFacts implements Prototyped, DAOConnected
	{
		/**
		 * @return PlatformUsersUserRegistrationFacts
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PlatformUsersUserRegistrationFactsDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PlatformUsersUserRegistrationFactsDAO');
		}
		
		/**
		 * @return ProtoPlatformUsersUserRegistrationFacts
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformUsersUserRegistrationFacts');
		}
		
		// your brilliant stuff goes here
	}
?>