<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-10 14:23:47                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformBaseRequest extends AutoPlatformBaseRequest implements Prototyped
	{
		/**
		 * @return PlatformBaseRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoPlatformBaseRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformBaseRequest');
		}
		
		// your brilliant stuff goes here
	}
?>