<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-23 11:20:04                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformSmsResponse extends AutoPlatformSmsResponse implements Prototyped
	{
		/**
		 * @return PlatformSmsResponse
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoPlatformSmsResponse
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformSmsResponse');
		}
		
		// your brilliant stuff goes here
	}
?>