<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-09 10:42:04                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformCommonNewsDraft extends AutoPlatformCommonNewsDraft implements Prototyped, DAOConnected
	{
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PlatformCommonNewsDraftDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PlatformCommonNewsDraftDAO');
		}
		
		/**
		 * @return ProtoPlatformCommonNewsDraft
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformCommonNewsDraft');
		}
		
		// your brilliant stuff goes here
	}
?>