<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-27 11:18:06                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformSocialFlowPages extends AutoPlatformSocialFlowPages implements Prototyped, DAOConnected
	{
		/**
		 * @return PlatformSocialFlowPages
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PlatformSocialFlowPagesDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PlatformSocialFlowPagesDAO');
		}
		
		/**
		 * @return ProtoPlatformSocialFlowPages
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformSocialFlowPages');
		}
		
		// your brilliant stuff goes here
	}
?>