<?php

/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-13 15:36:15                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
class PlatformSocialNameEnum extends Enum
{
    const
        FACEBOOK = 0,
        VK = 1;

    // implement me!
    protected static $names = [
        self::FACEBOOK => 'facebook',
        self::VK => 'vkontakte'
    ];


    public static function getByName($name)
    {
        $id = array_search($name,static::$names);

        if(is_null($id))
            throw new ServiceException('no social network');

        return new self($id);
    }
}

?>