<?php

/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-14 14:07:19                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
class PlatformSocialAppAdmin extends AutoPlatformSocialAppAdmin implements Prototyped, DAOConnected
{
    /**
     * @return PlatformSocialAppAdmin
     **/
    public static function create()
    {
        return new self;
    }

    /**
     * @return PlatformSocialAppAdminDAO
     **/
    public static function dao()
    {
        return Singleton::getInstance('PlatformSocialAppAdminDAO');
    }

    /**
     * @return ProtoPlatformSocialAppAdmin
     **/
    public static function proto()
    {
        return Singleton::getInstance('ProtoPlatformSocialAppAdmin');
    }


    public function add()
    {
        try {
            $request = (new self)->dao()->add($this);
        } catch (BaseException $e) {
            return null;
        }

        return $request;
    }

    /**
     * @return null|PlatformSocialAppAdminGroup[]
     */
    public function getAdminGroups()
    {
        try {

            return (new PlatformSocialAppAdminGroup())
                ->dao()
                ->getListByAdmin($this);

        } catch (ObjectNotFoundException $e) {
            return null;
        }
    }

    /**
     * @return null|PlatformSocialAppAdminPage[]
     */
    public function getAdminPages()
    {
        try {

            return (new PlatformSocialAppAdminPage())
                ->dao()
                ->getListByAdmin($this);

        } catch (ObjectNotFoundException $e) {
            return null;
        }
    }

    /**
     * @param $id
     * @return PlatformSocialAppAdminPage|null
     */
    public function getPageBySocialId($id)
    {
        try {
            return (new PlatformSocialAppAdminPage())
                ->dao()
                ->getByAdminAndSocialId($this, $id);
        }catch (ObjectNotFoundException $e)
        {
            return null;
        }
    }

    public function getGroupBySocialId($id)
    {
        try {
            return (new PlatformSocialAppAdminGroup())
                ->dao()
                ->getByAdminAndSocialId($this, $id);

        }catch(ObjectNotFoundException $e)
        {
            return null;
        }
    }

    public function drop()
    {
        try {
            (new self)->dao()->drop($this);
        } catch (Exception $e) {
            return null;
        }
    }

    public function update()
    {
        try {
            (new self)->dao()->save($this);
        } catch (Exception $e)
        {
            return null;
        }
    }

    // your brilliant stuff goes here
}

?>