<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-09 11:24:40                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformUsersAdminRole extends AutoPlatformUsersAdminRole implements Prototyped, DAOConnected
	{
		/**
		 * @return PlatformUsersAdminRole
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PlatformUsersAdminRoleDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PlatformUsersAdminRoleDAO');
		}
		
		/**
		 * @return ProtoPlatformUsersAdminRole
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformUsersAdminRole');
		}
		
		// your brilliant stuff goes here
	}
?>