<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-11 13:06:27                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformBaseResponse extends AutoPlatformBaseResponse implements Prototyped
	{
		/**
		 * @return PlatformBaseResponse
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoPlatformBaseResponse
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformBaseResponse');
		}
		
		// your brilliant stuff goes here
	}
?>