<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-14 14:07:19                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformSocialAppAdminPage extends AutoPlatformSocialAppAdminPage implements Prototyped, DAOConnected
	{
		/**
		 * @return PlatformSocialAppAdminPage
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PlatformSocialAppAdminPageDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PlatformSocialAppAdminPageDAO');
		}
		
		/**
		 * @return ProtoPlatformSocialAppAdminPage
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformSocialAppAdminPage');
		}

		public function add()
		{
			try {
				$response = (new self)->dao()->add($this);
			}catch(Exception $e)
			{
				return null;
			}

			return $response;
		}

		public function drop()
		{
			try {
				(new self)->dao()->drop($this);
			}catch(Exception $e)
			{
				return null;
			}
		}
		
		// your brilliant stuff goes here
	}
?>