<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-04-11 09:08:09                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformSocialPublishedLinkData extends AutoPlatformSocialPublishedLinkData implements Prototyped, DAOConnected
	{
		/**
		 * @return PlatformSocialPublishedLinkData
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PlatformSocialPublishedLinkDataDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PlatformSocialPublishedLinkDataDAO');
		}
		
		/**
		 * @return ProtoPlatformSocialPublishedLinkData
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformSocialPublishedLinkData');
		}
		
		// your brilliant stuff goes here
	}
?>