<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-13 12:13:25                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformPublisherApplication extends AutoPlatformPublisherApplication implements Prototyped, DAOConnected
	{
		/**
		 * @return PlatformPublisherApplication
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PlatformPublisherApplicationDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PlatformPublisherApplicationDAO');
		}
		
		/**
		 * @return ProtoPlatformPublisherApplication
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformPublisherApplication');
		}
		
		// your brilliant stuff goes here
	}
?>