<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-09 10:42:04                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformCommonNews extends AutoPlatformCommonNews implements Prototyped, DAOConnected
	{
		/**
		 * @return PlatformCommonNews
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PlatformCommonNewsDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PlatformCommonNewsDAO');
		}
		
		/**
		 * @return ProtoPlatformCommonNews
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformCommonNews');
		}
		
		// your brilliant stuff goes here
	}
?>