<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-08 13:10:19                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformCommonProject extends AutoPlatformCommonProject implements Prototyped, DAOConnected
	{
		/**
		 * @return PlatformCommonProject
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PlatformCommonProjectDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PlatformCommonProjectDAO');
		}
		
		/**
		 * @return ProtoPlatformCommonProject
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformCommonProject');
		}
		
		// your brilliant stuff goes here
	}
?>