<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-20 11:37:42                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformMultimediaImagesSize extends AutoPlatformMultimediaImagesSize implements Prototyped, DAOConnected
	{
		/**
		 * @return PlatformMultimediaImagesSize
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PlatformMultimediaImagesSizeDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PlatformMultimediaImagesSizeDAO');
		}
		
		/**
		 * @return ProtoPlatformMultimediaImagesSize
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformMultimediaImagesSize');
		}
		
		// your brilliant stuff goes here
	}
?>