<?php

/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-22 08:28:40                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
class PlatformUsersWhiteIpList extends AutoPlatformUsersWhiteIpList implements Prototyped, DAOConnected
{
    /**
     * @return PlatformUsersWhiteIpList
     **/
    public static function create()
    {
        return new self;
    }

    /**
     * @return PlatformUsersWhiteIpListDAO
     **/
    public static function dao()
    {
        return Singleton::getInstance('PlatformUsersWhiteIpListDAO');
    }

    /**
     * @return ProtoPlatformUsersWhiteIpList
     **/
    public static function proto()
    {
        return Singleton::getInstance('ProtoPlatformUsersWhiteIpList');
    }


    public static function isWhiteListIp($ip)
    {
        try {
            return self::dao()->getByIpAndActive($ip)->getActive();
        } catch (ObjectNotFoundException $e) {
            /**  */
        }
        return false;
    }

}

?>