<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-08 12:16:28                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformUsersAuthCommon extends AutoPlatformUsersAuthCommon implements Prototyped, DAOConnected
	{
		/**
		 * @return PlatformUsersAuthCommon
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PlatformUsersAuthCommonDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PlatformUsersAuthCommonDAO');
		}
		
		/**
		 * @return ProtoPlatformUsersAuthCommon
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformUsersAuthCommon');
		}
		
		// your brilliant stuff goes here
	}
?>