<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-22 08:15:04                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformUsersAdminProfile extends AutoPlatformUsersAdminProfile implements Prototyped, DAOConnected
	{
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PlatformUsersAdminProfileDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PlatformUsersAdminProfileDAO');
		}
		
		/**
		 * @return ProtoPlatformUsersAdminProfile
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformUsersAdminProfile');
		}
		
		// your brilliant stuff goes here
	}
?>