<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-15 10:16:42                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformCommonRubricData extends AutoPlatformCommonRubricData implements Prototyped, DAOConnected
	{
		/**
		 * @return PlatformCommonRubricData
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PlatformCommonRubricDataDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PlatformCommonRubricDataDAO');
		}
		
		/**
		 * @return ProtoPlatformCommonRubricData
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformCommonRubricData');
		}
		
		// your brilliant stuff goes here
	}
?>