<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-09 14:03:27                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformUsersAdminInfo extends AutoPlatformUsersAdminInfo implements Prototyped, DAOConnected
	{
		/**
		 * @return PlatformUsersAdminInfo
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PlatformUsersAdminInfoDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PlatformUsersAdminInfoDAO');
		}
		
		/**
		 * @return ProtoPlatformUsersAdminInfo
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformUsersAdminInfo');
		}
		
		// your brilliant stuff goes here
	}
?>