<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-13 12:21:44                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformSocialAppRequest extends AutoPlatformSocialAppRequest implements Prototyped
	{
		/**
		 * @return PlatformSocialAppRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoPlatformSocialAppRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformSocialAppRequest');
		}

		public function getSocialNetwork()
		{
			return parent::getSocialNetwork(); // TODO: Change the autogenerated stub
		}

		// your brilliant stuff goes here
	}
?>