<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-08 10:10:45                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformUsersUser extends AutoPlatformUsersUser implements Prototyped, DAOConnected
	{
		/**
		 * @return PlatformUsersUser
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PlatformUsersUserDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PlatformUsersUserDAO');
		}
		
		/**
		 * @return ProtoPlatformUsersUser
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformUsersUser');
		}
		
		// your brilliant stuff goes here
	}
?>