<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-23 13:20:59                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformAdminCodeRequest extends AutoPlatformAdminCodeRequest implements Prototyped
	{
		/**
		 * @return PlatformAdminCodeRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoPlatformAdminCodeRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformAdminCodeRequest');
		}
		
		// your brilliant stuff goes here
	}
?>