<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-23 12:25:38                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PlatformSendCodeRequest extends AutoPlatformSendCodeRequest implements Prototyped
	{
		/**
		 * @return PlatformSendCodeRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoPlatformSendCodeRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPlatformSendCodeRequest');
		}
		
		// your brilliant stuff goes here
	}
?>