<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-11 09:20:59                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class VkResponse extends AutoVkResponse implements Prototyped
	{
		/**
		 * @return VkResponse
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoVkResponse
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoVkResponse');
		}
		
		// your brilliant stuff goes here
	}
?>