<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-09 11:24:40                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformUsersAdminRole extends IdentifiableObject
	{
		protected $admin = null;
		protected $adminId = null;
		protected $role = null;
		protected $roleId = null;
		
		/**
		 * @return PlatformUsersAdmin
		**/
		public function getAdmin()
		{
			if (!$this->admin && $this->adminId) {
				$this->admin = PlatformUsersAdmin::dao()->getById($this->adminId);
			}
			
			return $this->admin;
		}
		
		public function getAdminId()
		{
			return $this->admin
				? $this->admin->getId()
				: $this->adminId;
		}
		
		/**
		 * @return PlatformUsersAdminRole
		**/
		public function setAdmin(PlatformUsersAdmin $admin)
		{
			$this->admin = $admin;
			$this->adminId = $admin ? $admin->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAdminRole
		**/
		public function setAdminId($id)
		{
			$this->admin = null;
			$this->adminId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAdminRole
		**/
		public function dropAdmin()
		{
			$this->admin = null;
			$this->adminId = null;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersRole
		**/
		public function getRole()
		{
			if (!$this->role && $this->roleId) {
				$this->role = PlatformUsersRole::dao()->getById($this->roleId);
			}
			
			return $this->role;
		}
		
		public function getRoleId()
		{
			return $this->role
				? $this->role->getId()
				: $this->roleId;
		}
		
		/**
		 * @return PlatformUsersAdminRole
		**/
		public function setRole(PlatformUsersRole $role)
		{
			$this->role = $role;
			$this->roleId = $role ? $role->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAdminRole
		**/
		public function setRoleId($id)
		{
			$this->role = null;
			$this->roleId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAdminRole
		**/
		public function dropRole()
		{
			$this->role = null;
			$this->roleId = null;
			
			return $this;
		}
	}
?>