<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-09 11:24:40                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformUsersModuleOperation extends IdentifiableObject
	{
		protected $module = null;
		protected $moduleId = null;
		protected $role = null;
		protected $roleId = null;
		protected $name = null;
		
		/**
		 * @return PlatformCommonModule
		**/
		public function getModule()
		{
			if (!$this->module && $this->moduleId) {
				$this->module = PlatformCommonModule::dao()->getById($this->moduleId);
			}
			
			return $this->module;
		}
		
		public function getModuleId()
		{
			return $this->module
				? $this->module->getId()
				: $this->moduleId;
		}
		
		/**
		 * @return PlatformUsersModuleOperation
		**/
		public function setModule(PlatformCommonModule $module)
		{
			$this->module = $module;
			$this->moduleId = $module ? $module->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersModuleOperation
		**/
		public function setModuleId($id)
		{
			$this->module = null;
			$this->moduleId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersModuleOperation
		**/
		public function dropModule()
		{
			$this->module = null;
			$this->moduleId = null;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersRole
		**/
		public function getRole()
		{
			if (!$this->role && $this->roleId) {
				$this->role = PlatformUsersRole::dao()->getById($this->roleId);
			}
			
			return $this->role;
		}
		
		public function getRoleId()
		{
			return $this->role
				? $this->role->getId()
				: $this->roleId;
		}
		
		/**
		 * @return PlatformUsersModuleOperation
		**/
		public function setRole(PlatformUsersRole $role)
		{
			$this->role = $role;
			$this->roleId = $role ? $role->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersModuleOperation
		**/
		public function setRoleId($id)
		{
			$this->role = null;
			$this->roleId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersModuleOperation
		**/
		public function dropRole()
		{
			$this->role = null;
			$this->roleId = null;
			
			return $this;
		}
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return PlatformUsersModuleOperation
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
	}
?>