<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-16 14:35:19                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModuleMultimediaAddImageOperationResponse extends ModuleMultimediaResponse
	{
		protected $IcoPath = null;
		
		public function getIcoPath()
		{
			return $this->IcoPath;
		}
		
		/**
		 * @return ModuleMultimediaAddImageOperationResponse
		**/
		public function setIcoPath($IcoPath)
		{
			$this->IcoPath = $IcoPath;
			
			return $this;
		}
	}
?>