<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-28 11:01:03                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformSocialFlow extends IdentifiableObject
	{
		protected $name = null;
		protected $accessToken = null;
		protected $secretKey = null;
		protected $deleted = false;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return PlatformSocialFlow
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getAccessToken()
		{
			return $this->accessToken;
		}
		
		/**
		 * @return PlatformSocialFlow
		**/
		public function setAccessToken($accessToken)
		{
			$this->accessToken = $accessToken;
			
			return $this;
		}
		
		public function getSecretKey()
		{
			return $this->secretKey;
		}
		
		/**
		 * @return PlatformSocialFlow
		**/
		public function setSecretKey($secretKey)
		{
			$this->secretKey = $secretKey;
			
			return $this;
		}
		
		public function getDeleted()
		{
			return $this->deleted;
		}
		
		public function isDeleted()
		{
			return $this->deleted;
		}
		
		/**
		 * @return PlatformSocialFlow
		**/
		public function setDeleted($deleted = null)
		{
			Assert::isTernaryBase($deleted);
			
			$this->deleted = $deleted;
			
			return $this;
		}
	}
?>