<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-09 10:44:52                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformCommonNews extends IdentifiableObject
	{
		protected $project = null;
		protected $projectId = null;
		protected $newsDraft = null;
		protected $newsDraftId = null;
		protected $newsPublished = null;
		protected $newsPublishedId = null;
		protected $createdAt = null;
		protected $publishedAt = null;
		protected $published = null;
		
		/**
		 * @return PlatformCommonProject
		**/
		public function getProject()
		{
			if (!$this->project && $this->projectId) {
				$this->project = PlatformCommonProject::dao()->getById($this->projectId);
			}
			
			return $this->project;
		}
		
		public function getProjectId()
		{
			return $this->project
				? $this->project->getId()
				: $this->projectId;
		}
		
		/**
		 * @return PlatformCommonNews
		**/
		public function setProject(PlatformCommonProject $project)
		{
			$this->project = $project;
			$this->projectId = $project ? $project->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNews
		**/
		public function setProjectId($id)
		{
			$this->project = null;
			$this->projectId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNews
		**/
		public function dropProject()
		{
			$this->project = null;
			$this->projectId = null;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function getNewsDraft()
		{
			if (!$this->newsDraft && $this->newsDraftId) {
				$this->newsDraft = PlatformCommonNewsDraft::dao()->getById($this->newsDraftId);
			}
			
			return $this->newsDraft;
		}
		
		public function getNewsDraftId()
		{
			return $this->newsDraft
				? $this->newsDraft->getId()
				: $this->newsDraftId;
		}
		
		/**
		 * @return PlatformCommonNews
		**/
		public function setNewsDraft(PlatformCommonNewsDraft $newsDraft = null)
		{
			$this->newsDraft = $newsDraft;
			$this->newsDraftId = $newsDraft ? $newsDraft->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNews
		**/
		public function setNewsDraftId($id = null)
		{
			$this->newsDraft = null;
			$this->newsDraftId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNews
		**/
		public function dropNewsDraft()
		{
			$this->newsDraft = null;
			$this->newsDraftId = null;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNewsPublished
		**/
		public function getNewsPublished()
		{
			if (!$this->newsPublished && $this->newsPublishedId) {
				$this->newsPublished = PlatformCommonNewsPublished::dao()->getById($this->newsPublishedId);
			}
			
			return $this->newsPublished;
		}
		
		public function getNewsPublishedId()
		{
			return $this->newsPublished
				? $this->newsPublished->getId()
				: $this->newsPublishedId;
		}
		
		/**
		 * @return PlatformCommonNews
		**/
		public function setNewsPublished(PlatformCommonNewsPublished $newsPublished = null)
		{
			$this->newsPublished = $newsPublished;
			$this->newsPublishedId = $newsPublished ? $newsPublished->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNews
		**/
		public function setNewsPublishedId($id = null)
		{
			$this->newsPublished = null;
			$this->newsPublishedId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNews
		**/
		public function dropNewsPublished()
		{
			$this->newsPublished = null;
			$this->newsPublishedId = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getCreatedAt()
		{
			return $this->createdAt;
		}
		
		/**
		 * @return PlatformCommonNews
		**/
		public function setCreatedAt(TimestampTZ $createdAt = null)
		{
			$this->createdAt = $createdAt;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNews
		**/
		public function dropCreatedAt()
		{
			$this->createdAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getPublishedAt()
		{
			return $this->publishedAt;
		}
		
		/**
		 * @return PlatformCommonNews
		**/
		public function setPublishedAt(TimestampTZ $publishedAt = null)
		{
			$this->publishedAt = $publishedAt;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNews
		**/
		public function dropPublishedAt()
		{
			$this->publishedAt = null;
			
			return $this;
		}
		
		public function getPublished()
		{
			return $this->published;
		}
		
		public function isPublished()
		{
			return $this->published;
		}
		
		/**
		 * @return PlatformCommonNews
		**/
		public function setPublished($published = null)
		{
			Assert::isTernaryBase($published);
			
			$this->published = $published;
			
			return $this;
		}
	}
?>