<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-08 11:57:41                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformUsersAuthType extends IdentifiableObject
	{
		protected $name = null;
		protected $settings = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return PlatformUsersAuthType
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		/**
		 * @return Hstore
		**/
		public function getSettings()
		{
			return $this->settings;
		}
		
		/**
		 * @return PlatformUsersAuthType
		**/
		public function setSettings(Hstore $settings = null)
		{
			$this->settings = $settings;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAuthType
		**/
		public function dropSettings()
		{
			$this->settings = null;
			
			return $this;
		}
	}
?>