<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-09 12:53:08                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformCommonNewsDraft extends IdentifiableObject
	{
		protected $news = null;
		protected $newsId = null;
		protected $admin = null;
		protected $adminId = null;
		protected $title = null;
		protected $anons = null;
		protected $text = null;
		protected $metaDescription = null;
		protected $metaKeywords = null;
		protected $rubrics = null;
		protected $modifiedAt = null;
		protected $preview = null;
		
		/**
		 * @return PlatformCommonNews
		**/
		public function getNews()
		{
			if (!$this->news && $this->newsId) {
				$this->news = PlatformCommonNews::dao()->getById($this->newsId);
			}
			
			return $this->news;
		}
		
		public function getNewsId()
		{
			return $this->news
				? $this->news->getId()
				: $this->newsId;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function setNews(PlatformCommonNews $news = null)
		{
			$this->news = $news;
			$this->newsId = $news ? $news->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function setNewsId($id = null)
		{
			$this->news = null;
			$this->newsId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function dropNews()
		{
			$this->news = null;
			$this->newsId = null;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAdmin
		**/
		public function getAdmin()
		{
			if (!$this->admin && $this->adminId) {
				$this->admin = PlatformUsersAdmin::dao()->getById($this->adminId);
			}
			
			return $this->admin;
		}
		
		public function getAdminId()
		{
			return $this->admin
				? $this->admin->getId()
				: $this->adminId;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function setAdmin(PlatformUsersAdmin $admin = null)
		{
			$this->admin = $admin;
			$this->adminId = $admin ? $admin->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function setAdminId($id = null)
		{
			$this->admin = null;
			$this->adminId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function dropAdmin()
		{
			$this->admin = null;
			$this->adminId = null;
			
			return $this;
		}
		
		public function getTitle()
		{
			return $this->title;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function setTitle($title)
		{
			$this->title = $title;
			
			return $this;
		}
		
		public function getAnons()
		{
			return $this->anons;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function setAnons($anons)
		{
			$this->anons = $anons;
			
			return $this;
		}
		
		public function getText()
		{
			return $this->text;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function setText($text)
		{
			$this->text = $text;
			
			return $this;
		}
		
		public function getMetaDescription()
		{
			return $this->metaDescription;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function setMetaDescription($metaDescription)
		{
			$this->metaDescription = $metaDescription;
			
			return $this;
		}
		
		public function getMetaKeywords()
		{
			return $this->metaKeywords;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function setMetaKeywords($metaKeywords)
		{
			$this->metaKeywords = $metaKeywords;
			
			return $this;
		}
		
		/**
		 * @return Hstore
		**/
		public function getRubrics()
		{
			return $this->rubrics;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function setRubrics(Hstore $rubrics = null)
		{
			$this->rubrics = $rubrics;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function dropRubrics()
		{
			$this->rubrics = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getModifiedAt()
		{
			return $this->modifiedAt;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function setModifiedAt(TimestampTZ $modifiedAt = null)
		{
			$this->modifiedAt = $modifiedAt;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function dropModifiedAt()
		{
			$this->modifiedAt = null;
			
			return $this;
		}
		
		public function getPreview()
		{
			return $this->preview;
		}
		
		/**
		 * @return PlatformCommonNewsDraft
		**/
		public function setPreview($preview)
		{
			$this->preview = $preview;
			
			return $this;
		}
	}
?>