<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-06 11:21:14                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModuleRubricsSearchOperationRequest extends ModuleRubricsRequest
	{
		protected $draw = null;
		protected $offset = null;
		protected $limit = null;
		protected $ofCreatedAt = null;
		protected $toCreatedAt = null;
		protected $ofModifiedAt = null;
		protected $toModifiedAt = null;
		
		public function getDraw()
		{
			return $this->draw;
		}
		
		/**
		 * @return ModuleRubricsSearchOperationRequest
		**/
		public function setDraw($draw)
		{
			$this->draw = $draw;
			
			return $this;
		}
		
		public function getOffset()
		{
			return $this->offset;
		}
		
		/**
		 * @return ModuleRubricsSearchOperationRequest
		**/
		public function setOffset($offset)
		{
			$this->offset = $offset;
			
			return $this;
		}
		
		public function getLimit()
		{
			return $this->limit;
		}
		
		/**
		 * @return ModuleRubricsSearchOperationRequest
		**/
		public function setLimit($limit)
		{
			$this->limit = $limit;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getOfCreatedAt()
		{
			return $this->ofCreatedAt;
		}
		
		/**
		 * @return ModuleRubricsSearchOperationRequest
		**/
		public function setOfCreatedAt(TimestampTZ $ofCreatedAt = null)
		{
			$this->ofCreatedAt = $ofCreatedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleRubricsSearchOperationRequest
		**/
		public function dropOfCreatedAt()
		{
			$this->ofCreatedAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getToCreatedAt()
		{
			return $this->toCreatedAt;
		}
		
		/**
		 * @return ModuleRubricsSearchOperationRequest
		**/
		public function setToCreatedAt(TimestampTZ $toCreatedAt = null)
		{
			$this->toCreatedAt = $toCreatedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleRubricsSearchOperationRequest
		**/
		public function dropToCreatedAt()
		{
			$this->toCreatedAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getOfModifiedAt()
		{
			return $this->ofModifiedAt;
		}
		
		/**
		 * @return ModuleRubricsSearchOperationRequest
		**/
		public function setOfModifiedAt(TimestampTZ $ofModifiedAt = null)
		{
			$this->ofModifiedAt = $ofModifiedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleRubricsSearchOperationRequest
		**/
		public function dropOfModifiedAt()
		{
			$this->ofModifiedAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getToModifiedAt()
		{
			return $this->toModifiedAt;
		}
		
		/**
		 * @return ModuleRubricsSearchOperationRequest
		**/
		public function setToModifiedAt(TimestampTZ $toModifiedAt = null)
		{
			$this->toModifiedAt = $toModifiedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleRubricsSearchOperationRequest
		**/
		public function dropToModifiedAt()
		{
			$this->toModifiedAt = null;
			
			return $this;
		}
	}
?>