<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-14 14:30:21                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformSocialAppAdmin extends IdentifiableObject
	{
		protected $app = null;
		protected $appId = null;
		protected $appAccessToken = null;
		protected $name = null;
		protected $socialAdminId = null;
		
		/**
		 * @return PlatformSocialApp
		**/
		public function getApp()
		{
			if (!$this->app && $this->appId) {
				$this->app = PlatformSocialApp::dao()->getById($this->appId);
			}
			
			return $this->app;
		}
		
		public function getAppId()
		{
			return $this->app
				? $this->app->getId()
				: $this->appId;
		}
		
		/**
		 * @return PlatformSocialAppAdmin
		**/
		public function setApp(PlatformSocialApp $app)
		{
			$this->app = $app;
			$this->appId = $app ? $app->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialAppAdmin
		**/
		public function setAppId($id)
		{
			$this->app = null;
			$this->appId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialAppAdmin
		**/
		public function dropApp()
		{
			$this->app = null;
			$this->appId = null;
			
			return $this;
		}
		
		public function getAppAccessToken()
		{
			return $this->appAccessToken;
		}
		
		/**
		 * @return PlatformSocialAppAdmin
		**/
		public function setAppAccessToken($appAccessToken)
		{
			$this->appAccessToken = $appAccessToken;
			
			return $this;
		}
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return PlatformSocialAppAdmin
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getSocialAdminId()
		{
			return $this->socialAdminId;
		}
		
		/**
		 * @return PlatformSocialAppAdmin
		**/
		public function setSocialAdminId($socialAdminId)
		{
			$this->socialAdminId = $socialAdminId;
			
			return $this;
		}
	}
?>