<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-13 12:21:44                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformSocialAppRequest extends PlatformBaseRequest
	{
		protected $name = null;
		protected $socialNetwork = null;
		protected $appId = null;
		protected $appSecretKey = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return PlatformSocialAppRequest
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getSocialNetwork()
		{
			return $this->socialNetwork;
		}
		
		/**
		 * @return PlatformSocialAppRequest
		**/
		public function setSocialNetwork($socialNetwork)
		{
			$this->socialNetwork = $socialNetwork;
			
			return $this;
		}
		
		public function getAppId()
		{
			return $this->appId;
		}
		
		/**
		 * @return PlatformSocialAppRequest
		**/
		public function setAppId($appId)
		{
			$this->appId = $appId;
			
			return $this;
		}
		
		public function getAppSecretKey()
		{
			return $this->appSecretKey;
		}
		
		/**
		 * @return PlatformSocialAppRequest
		**/
		public function setAppSecretKey($appSecretKey)
		{
			$this->appSecretKey = $appSecretKey;
			
			return $this;
		}
	}
?>