<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-12 16:21:58                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModuleRubricsRequest extends PlatformBaseRequest
	{
		protected $rubricId = null;
		protected $projectId = null;
		protected $adminId = null;
		protected $RubricDataId = null;
		protected $name = null;
		protected $path = null;
		protected $enabled = null;
		protected $createdAt = null;
		protected $modifiedAt = null;
		protected $shortName = null;
		protected $description = null;
		protected $metaDescription = null;
		protected $metaKeywords = null;
		
		public function getRubricId()
		{
			return $this->rubricId;
		}
		
		/**
		 * @return ModuleRubricsRequest
		**/
		public function setRubricId($rubricId)
		{
			$this->rubricId = $rubricId;
			
			return $this;
		}
		
		public function getProjectId()
		{
			return $this->projectId;
		}
		
		/**
		 * @return ModuleRubricsRequest
		**/
		public function setProjectId($projectId)
		{
			$this->projectId = $projectId;
			
			return $this;
		}
		
		public function getAdminId()
		{
			return $this->adminId;
		}
		
		/**
		 * @return ModuleRubricsRequest
		**/
		public function setAdminId($adminId)
		{
			$this->adminId = $adminId;
			
			return $this;
		}
		
		public function getRubricDataId()
		{
			return $this->RubricDataId;
		}
		
		/**
		 * @return ModuleRubricsRequest
		**/
		public function setRubricDataId($RubricDataId)
		{
			$this->RubricDataId = $RubricDataId;
			
			return $this;
		}
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return ModuleRubricsRequest
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getPath()
		{
			return $this->path;
		}
		
		/**
		 * @return ModuleRubricsRequest
		**/
		public function setPath($path)
		{
			$this->path = $path;
			
			return $this;
		}
		
		public function getEnabled()
		{
			return $this->enabled;
		}
		
		public function isEnabled()
		{
			return $this->enabled;
		}
		
		/**
		 * @return ModuleRubricsRequest
		**/
		public function setEnabled($enabled = null)
		{
			Assert::isTernaryBase($enabled);
			
			$this->enabled = $enabled;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getCreatedAt()
		{
			return $this->createdAt;
		}
		
		/**
		 * @return ModuleRubricsRequest
		**/
		public function setCreatedAt(TimestampTZ $createdAt = null)
		{
			$this->createdAt = $createdAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleRubricsRequest
		**/
		public function dropCreatedAt()
		{
			$this->createdAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getModifiedAt()
		{
			return $this->modifiedAt;
		}
		
		/**
		 * @return ModuleRubricsRequest
		**/
		public function setModifiedAt(TimestampTZ $modifiedAt = null)
		{
			$this->modifiedAt = $modifiedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleRubricsRequest
		**/
		public function dropModifiedAt()
		{
			$this->modifiedAt = null;
			
			return $this;
		}
		
		public function getShortName()
		{
			return $this->shortName;
		}
		
		/**
		 * @return ModuleRubricsRequest
		**/
		public function setShortName($shortName)
		{
			$this->shortName = $shortName;
			
			return $this;
		}
		
		public function getDescription()
		{
			return $this->description;
		}
		
		/**
		 * @return ModuleRubricsRequest
		**/
		public function setDescription($description)
		{
			$this->description = $description;
			
			return $this;
		}
		
		public function getMetaDescription()
		{
			return $this->metaDescription;
		}
		
		/**
		 * @return ModuleRubricsRequest
		**/
		public function setMetaDescription($metaDescription)
		{
			$this->metaDescription = $metaDescription;
			
			return $this;
		}
		
		public function getMetaKeywords()
		{
			return $this->metaKeywords;
		}
		
		/**
		 * @return ModuleRubricsRequest
		**/
		public function setMetaKeywords($metaKeywords)
		{
			$this->metaKeywords = $metaKeywords;
			
			return $this;
		}
	}
?>