<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-27 11:30:08                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformUsersAdminProfile extends IdentifiableObject
	{
		protected $admin = null;
		protected $adminId = null;
		protected $lastName = null;
		protected $firstName = null;
		protected $middleName = null;
		protected $createdAt = null;
		protected $passwordExpiresTime = null;
		protected $alias = null;
		protected $settings = null;
		protected $status = null;
		
		/**
		 * @return PlatformUsersAdmin
		**/
		public function getAdmin()
		{
			if (!$this->admin && $this->adminId) {
				$this->admin = PlatformUsersAdmin::dao()->getById($this->adminId);
			}
			
			return $this->admin;
		}
		
		public function getAdminId()
		{
			return $this->admin
				? $this->admin->getId()
				: $this->adminId;
		}
		
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public function setAdmin(PlatformUsersAdmin $admin)
		{
			$this->admin = $admin;
			$this->adminId = $admin ? $admin->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public function setAdminId($id)
		{
			$this->admin = null;
			$this->adminId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public function dropAdmin()
		{
			$this->admin = null;
			$this->adminId = null;
			
			return $this;
		}
		
		public function getLastName()
		{
			return $this->lastName;
		}
		
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public function setLastName($lastName)
		{
			$this->lastName = $lastName;
			
			return $this;
		}
		
		public function getFirstName()
		{
			return $this->firstName;
		}
		
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public function setFirstName($firstName)
		{
			$this->firstName = $firstName;
			
			return $this;
		}
		
		public function getMiddleName()
		{
			return $this->middleName;
		}
		
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public function setMiddleName($middleName)
		{
			$this->middleName = $middleName;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getCreatedAt()
		{
			return $this->createdAt;
		}
		
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public function setCreatedAt(TimestampTZ $createdAt)
		{
			$this->createdAt = $createdAt;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public function dropCreatedAt()
		{
			$this->createdAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getPasswordExpiresTime()
		{
			return $this->passwordExpiresTime;
		}
		
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public function setPasswordExpiresTime(TimestampTZ $passwordExpiresTime)
		{
			$this->passwordExpiresTime = $passwordExpiresTime;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public function dropPasswordExpiresTime()
		{
			$this->passwordExpiresTime = null;
			
			return $this;
		}
		
		/**
		 * @return Hstore
		**/
		public function getAlias()
		{
			return $this->alias;
		}
		
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public function setAlias(Hstore $alias = null)
		{
			$this->alias = $alias;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public function dropAlias()
		{
			$this->alias = null;
			
			return $this;
		}
		
		/**
		 * @return Hstore
		**/
		public function getSettings()
		{
			return $this->settings;
		}
		
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public function setSettings(Hstore $settings = null)
		{
			$this->settings = $settings;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public function dropSettings()
		{
			$this->settings = null;
			
			return $this;
		}
		
		public function getStatus()
		{
			return $this->status;
		}
		
		/**
		 * @return PlatformUsersAdminProfile
		**/
		public function setStatus($status)
		{
			$this->status = $status;
			
			return $this;
		}
	}
?>