<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-23 10:27:54                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModuleMultimediaGetImageOperationRequest extends ModuleMultimediaRequest
	{
		protected $sizesId = null;
		
		public function getSizesId()
		{
			return $this->sizesId;
		}
		
		/**
		 * @return ModuleMultimediaGetImageOperationRequest
		**/
		public function setSizesId($sizesId)
		{
			$this->sizesId = $sizesId;
			
			return $this;
		}
	}
?>