<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-01-27 11:28:58                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformCommonRubric extends IdentifiableObject
	{
		protected $project = null;
		protected $projectId = null;
		protected $rubricData = null;
		protected $rubricDataId = null;
		protected $name = null;
		protected $path = null;
		protected $enabled = false;
		protected $createdAt = null;
		protected $modifiedAt = null;
		
		/**
		 * @return PlatformCommonProject
		**/
		public function getProject()
		{
			if (!$this->project && $this->projectId) {
				$this->project = PlatformCommonProject::dao()->getById($this->projectId);
			}
			
			return $this->project;
		}
		
		public function getProjectId()
		{
			return $this->project
				? $this->project->getId()
				: $this->projectId;
		}
		
		/**
		 * @return PlatformCommonRubric
		**/
		public function setProject(PlatformCommonProject $project = null)
		{
			$this->project = $project;
			$this->projectId = $project ? $project->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonRubric
		**/
		public function setProjectId($id = null)
		{
			$this->project = null;
			$this->projectId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonRubric
		**/
		public function dropProject()
		{
			$this->project = null;
			$this->projectId = null;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonRubricData
		**/
		public function getRubricData()
		{
			if (!$this->rubricData && $this->rubricDataId) {
				$this->rubricData = PlatformCommonRubricData::dao()->getById($this->rubricDataId);
			}
			
			return $this->rubricData;
		}
		
		public function getRubricDataId()
		{
			return $this->rubricData
				? $this->rubricData->getId()
				: $this->rubricDataId;
		}
		
		/**
		 * @return PlatformCommonRubric
		**/
		public function setRubricData(PlatformCommonRubricData $rubricData = null)
		{
			$this->rubricData = $rubricData;
			$this->rubricDataId = $rubricData ? $rubricData->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonRubric
		**/
		public function setRubricDataId($id = null)
		{
			$this->rubricData = null;
			$this->rubricDataId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonRubric
		**/
		public function dropRubricData()
		{
			$this->rubricData = null;
			$this->rubricDataId = null;
			
			return $this;
		}
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return PlatformCommonRubric
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getPath()
		{
			return $this->path;
		}
		
		/**
		 * @return PlatformCommonRubric
		**/
		public function setPath($path)
		{
			$this->path = $path;
			
			return $this;
		}
		
		public function getEnabled()
		{
			return $this->enabled;
		}
		
		public function isEnabled()
		{
			return $this->enabled;
		}
		
		/**
		 * @return PlatformCommonRubric
		**/
		public function setEnabled($enabled = false)
		{
			$this->enabled = ($enabled === true);
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getCreatedAt()
		{
			return $this->createdAt;
		}
		
		/**
		 * @return PlatformCommonRubric
		**/
		public function setCreatedAt(TimestampTZ $createdAt = null)
		{
			$this->createdAt = $createdAt;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonRubric
		**/
		public function dropCreatedAt()
		{
			$this->createdAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getModifiedAt()
		{
			return $this->modifiedAt;
		}
		
		/**
		 * @return PlatformCommonRubric
		**/
		public function setModifiedAt(TimestampTZ $modifiedAt = null)
		{
			$this->modifiedAt = $modifiedAt;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonRubric
		**/
		public function dropModifiedAt()
		{
			$this->modifiedAt = null;
			
			return $this;
		}
	}
?>