<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-08 10:10:45                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformUsersUserInfo extends IdentifiableObject
	{
		protected $user = null;
		protected $userId = null;
		protected $lastName = null;
		protected $firstName = null;
		protected $middleName = null;
		protected $birthday = null;
		protected $settings = null;
		protected $openId = null;
		protected $registredAt = null;
		protected $createdAt = null;
		protected $registred = null;
		protected $lastLogin = null;
		protected $signature = null;
		protected $preview = null;
		protected $previewImageTypeId = null;
		protected $phone = null;
		
		/**
		 * @return PlatformUsersUser
		**/
		public function getUser()
		{
			if (!$this->user && $this->userId) {
				$this->user = PlatformUsersUser::dao()->getById($this->userId);
			}
			
			return $this->user;
		}
		
		public function getUserId()
		{
			return $this->user
				? $this->user->getId()
				: $this->userId;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setUser(PlatformUsersUser $user)
		{
			$this->user = $user;
			$this->userId = $user ? $user->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setUserId($id)
		{
			$this->user = null;
			$this->userId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function dropUser()
		{
			$this->user = null;
			$this->userId = null;
			
			return $this;
		}
		
		public function getLastName()
		{
			return $this->lastName;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setLastName($lastName)
		{
			$this->lastName = $lastName;
			
			return $this;
		}
		
		public function getFirstName()
		{
			return $this->firstName;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setFirstName($firstName)
		{
			$this->firstName = $firstName;
			
			return $this;
		}
		
		public function getMiddleName()
		{
			return $this->middleName;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setMiddleName($middleName)
		{
			$this->middleName = $middleName;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getBirthday()
		{
			return $this->birthday;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setBirthday(TimestampTZ $birthday)
		{
			$this->birthday = $birthday;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function dropBirthday()
		{
			$this->birthday = null;
			
			return $this;
		}
		
		/**
		 * @return Hstore
		**/
		public function getSettings()
		{
			return $this->settings;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setSettings(Hstore $settings)
		{
			$this->settings = $settings;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function dropSettings()
		{
			$this->settings = null;
			
			return $this;
		}
		
		public function getOpenId()
		{
			return $this->openId;
		}
		
		public function isOpenId()
		{
			return $this->openId;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setOpenId($openId = false)
		{
			$this->openId = ($openId === true);
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getRegistredAt()
		{
			return $this->registredAt;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setRegistredAt(TimestampTZ $registredAt)
		{
			$this->registredAt = $registredAt;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function dropRegistredAt()
		{
			$this->registredAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getCreatedAt()
		{
			return $this->createdAt;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setCreatedAt(TimestampTZ $createdAt)
		{
			$this->createdAt = $createdAt;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function dropCreatedAt()
		{
			$this->createdAt = null;
			
			return $this;
		}
		
		public function getRegistred()
		{
			return $this->registred;
		}
		
		public function isRegistred()
		{
			return $this->registred;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setRegistred($registred = false)
		{
			$this->registred = ($registred === true);
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getLastLogin()
		{
			return $this->lastLogin;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setLastLogin(TimestampTZ $lastLogin = null)
		{
			$this->lastLogin = $lastLogin;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function dropLastLogin()
		{
			$this->lastLogin = null;
			
			return $this;
		}
		
		public function getSignature()
		{
			return $this->signature;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setSignature($signature)
		{
			$this->signature = $signature;
			
			return $this;
		}
		
		public function getPreview()
		{
			return $this->preview;
		}
		
		public function isPreview()
		{
			return $this->preview;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setPreview($preview = false)
		{
			$this->preview = ($preview === true);
			
			return $this;
		}
		
		public function getPreviewImageTypeId()
		{
			return $this->previewImageTypeId;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setPreviewImageTypeId($previewImageTypeId)
		{
			$this->previewImageTypeId = $previewImageTypeId;
			
			return $this;
		}
		
		public function getPhone()
		{
			return $this->phone;
		}
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function setPhone($phone)
		{
			$this->phone = $phone;
			
			return $this;
		}
	}
?>