<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-11 09:20:59                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoVkRequest
	{
		protected $method = null;
		protected $accessToken = null;
		protected $groupId = null;
		protected $friendsOnly = null;
		protected $fromGroup = true;
		protected $message = null;
		protected $attachments = null;
		protected $imgUrl = null;
		
		public function getMethod()
		{
			return $this->method;
		}
		
		/**
		 * @return VkRequest
		**/
		public function setMethod($method)
		{
			$this->method = $method;
			
			return $this;
		}
		
		public function getAccessToken()
		{
			return $this->accessToken;
		}
		
		/**
		 * @return VkRequest
		**/
		public function setAccessToken($accessToken)
		{
			$this->accessToken = $accessToken;
			
			return $this;
		}
		
		public function getGroupId()
		{
			return $this->groupId;
		}
		
		/**
		 * @return VkRequest
		**/
		public function setGroupId($groupId)
		{
			$this->groupId = $groupId;
			
			return $this;
		}
		
		public function getFriendsOnly()
		{
			return $this->friendsOnly;
		}
		
		/**
		 * @return VkRequest
		**/
		public function setFriendsOnly($friendsOnly)
		{
			$this->friendsOnly = $friendsOnly;
			
			return $this;
		}
		
		public function getFromGroup()
		{
			return $this->fromGroup;
		}
		
		public function isFromGroup()
		{
			return $this->fromGroup;
		}
		
		/**
		 * @return VkRequest
		**/
		public function setFromGroup($fromGroup = null)
		{
			Assert::isTernaryBase($fromGroup);
			
			$this->fromGroup = $fromGroup;
			
			return $this;
		}
		
		public function getMessage()
		{
			return $this->message;
		}
		
		/**
		 * @return VkRequest
		**/
		public function setMessage($message)
		{
			$this->message = $message;
			
			return $this;
		}
		
		public function getAttachments()
		{
			return $this->attachments;
		}
		
		/**
		 * @return VkRequest
		**/
		public function setAttachments($attachments)
		{
			$this->attachments = $attachments;
			
			return $this;
		}
		
		public function getImgUrl()
		{
			return $this->imgUrl;
		}
		
		/**
		 * @return VkRequest
		**/
		public function setImgUrl($imgUrl)
		{
			$this->imgUrl = $imgUrl;
			
			return $this;
		}
	}
?>