<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-27 09:47:05                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModuleMultimediaGetPreviewListResponse extends ModuleMultimediaResponse
	{
		protected $data = null;
		
		public function getData()
		{
			return $this->data;
		}
		
		/**
		 * @return ModuleMultimediaGetPreviewListResponse
		**/
		public function setData($data)
		{
			$this->data = $data;
			
			return $this;
		}
	}
?>