<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-24 10:23:21                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformAdminCodeRequest extends PlatformBaseRequest
	{
		protected $code = null;
		protected $createdAt = null;
		protected $active = null;
		protected $type = null;
		protected $typeId = null;
		protected $admin = null;
		protected $adminId = null;
		
		public function getCode()
		{
			return $this->code;
		}
		
		/**
		 * @return PlatformAdminCodeRequest
		**/
		public function setCode($code)
		{
			$this->code = $code;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getCreatedAt()
		{
			return $this->createdAt;
		}
		
		/**
		 * @return PlatformAdminCodeRequest
		**/
		public function setCreatedAt(TimestampTZ $createdAt)
		{
			$this->createdAt = $createdAt;
			
			return $this;
		}
		
		/**
		 * @return PlatformAdminCodeRequest
		**/
		public function dropCreatedAt()
		{
			$this->createdAt = null;
			
			return $this;
		}
		
		public function getActive()
		{
			return $this->active;
		}
		
		public function isActive()
		{
			return $this->active;
		}
		
		/**
		 * @return PlatformAdminCodeRequest
		**/
		public function setActive($active = null)
		{
			Assert::isTernaryBase($active);
			
			$this->active = $active;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAdminCodeTypeEnum
		**/
		public function getType()
		{
			if (!$this->type && $this->typeId) {
				$this->type = new PlatformUsersAdminCodeTypeEnum($this->typeId);
			}
			
			return $this->type;
		}
		
		public function getTypeId()
		{
			return $this->type
				? $this->type->getId()
				: $this->typeId;
		}
		
		/**
		 * @return PlatformAdminCodeRequest
		**/
		public function setType(PlatformUsersAdminCodeTypeEnum $type)
		{
			$this->type = $type;
			$this->typeId = $type ? $type->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformAdminCodeRequest
		**/
		public function setTypeId($id)
		{
			$this->type = null;
			$this->typeId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformAdminCodeRequest
		**/
		public function dropType()
		{
			$this->type = null;
			$this->typeId = null;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAdmin
		**/
		public function getAdmin()
		{
			if (!$this->admin && $this->adminId) {
				$this->admin = PlatformUsersAdmin::dao()->getById($this->adminId);
			}
			
			return $this->admin;
		}
		
		public function getAdminId()
		{
			return $this->admin
				? $this->admin->getId()
				: $this->adminId;
		}
		
		/**
		 * @return PlatformAdminCodeRequest
		**/
		public function setAdmin(PlatformUsersAdmin $admin)
		{
			$this->admin = $admin;
			$this->adminId = $admin ? $admin->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformAdminCodeRequest
		**/
		public function setAdminId($id)
		{
			$this->admin = null;
			$this->adminId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformAdminCodeRequest
		**/
		public function dropAdmin()
		{
			$this->admin = null;
			$this->adminId = null;
			
			return $this;
		}
	}
?>