<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-04-08 11:53:07                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformSocialApp extends IdentifiableObject
	{
		protected $admin = null;
		protected $adminId = null;
		protected $name = null;
		protected $socialNetwork = null;
		protected $appId = null;
		protected $appSecretKey = null;
		protected $createdAt = null;
		protected $picture = false;
		
		/**
		 * @return PlatformUsersAdmin
		**/
		public function getAdmin()
		{
			if (!$this->admin && $this->adminId) {
				$this->admin = PlatformUsersAdmin::dao()->getById($this->adminId);
			}
			
			return $this->admin;
		}
		
		public function getAdminId()
		{
			return $this->admin
				? $this->admin->getId()
				: $this->adminId;
		}
		
		/**
		 * @return PlatformSocialApp
		**/
		public function setAdmin(PlatformUsersAdmin $admin)
		{
			$this->admin = $admin;
			$this->adminId = $admin ? $admin->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialApp
		**/
		public function setAdminId($id)
		{
			$this->admin = null;
			$this->adminId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialApp
		**/
		public function dropAdmin()
		{
			$this->admin = null;
			$this->adminId = null;
			
			return $this;
		}
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return PlatformSocialApp
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialNameEnum
		**/
		public function getSocialNetwork()
		{
			return $this->socialNetwork;
		}
		
		/**
		 * @return PlatformSocialApp
		**/
		public function setSocialNetwork(PlatformSocialNameEnum $socialNetwork)
		{
			$this->socialNetwork = $socialNetwork;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialApp
		**/
		public function dropSocialNetwork()
		{
			$this->socialNetwork = null;
			
			return $this;
		}
		
		public function getAppId()
		{
			return $this->appId;
		}
		
		/**
		 * @return PlatformSocialApp
		**/
		public function setAppId($appId)
		{
			$this->appId = $appId;
			
			return $this;
		}
		
		public function getAppSecretKey()
		{
			return $this->appSecretKey;
		}
		
		/**
		 * @return PlatformSocialApp
		**/
		public function setAppSecretKey($appSecretKey)
		{
			$this->appSecretKey = $appSecretKey;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getCreatedAt()
		{
			return $this->createdAt;
		}
		
		/**
		 * @return PlatformSocialApp
		**/
		public function setCreatedAt(TimestampTZ $createdAt)
		{
			$this->createdAt = $createdAt;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialApp
		**/
		public function dropCreatedAt()
		{
			$this->createdAt = null;
			
			return $this;
		}
		
		public function getPicture()
		{
			return $this->picture;
		}
		
		public function isPicture()
		{
			return $this->picture;
		}
		
		/**
		 * @return PlatformSocialApp
		**/
		public function setPicture($picture = null)
		{
			Assert::isTernaryBase($picture);
			
			$this->picture = $picture;
			
			return $this;
		}
	}
?>