<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-04-08 13:17:18                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModuleMultimediaGetImageOperationResponse extends ModuleMultimediaResponse
	{
		protected $imagesSizes = null;
		protected $imagesPreviewSizes = null;
		protected $imagesPreviewSizesId = null;
		protected $multimediaHost = null;
		
		public function getImagesSizes()
		{
			return $this->imagesSizes;
		}
		
		/**
		 * @return ModuleMultimediaGetImageOperationResponse
		**/
		public function setImagesSizes($imagesSizes)
		{
			$this->imagesSizes = $imagesSizes;
			
			return $this;
		}
		
		/**
		 * @return PlatformMultimediaImagesSize
		**/
		public function getImagesPreviewSizes()
		{
			if (!$this->imagesPreviewSizes && $this->imagesPreviewSizesId) {
				$this->imagesPreviewSizes = PlatformMultimediaImagesSize::dao()->getById($this->imagesPreviewSizesId);
			}
			
			return $this->imagesPreviewSizes;
		}
		
		public function getImagesPreviewSizesId()
		{
			return $this->imagesPreviewSizes
				? $this->imagesPreviewSizes->getId()
				: $this->imagesPreviewSizesId;
		}
		
		/**
		 * @return ModuleMultimediaGetImageOperationResponse
		**/
		public function setImagesPreviewSizes(PlatformMultimediaImagesSize $imagesPreviewSizes = null)
		{
			$this->imagesPreviewSizes = $imagesPreviewSizes;
			$this->imagesPreviewSizesId = $imagesPreviewSizes ? $imagesPreviewSizes->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return ModuleMultimediaGetImageOperationResponse
		**/
		public function setImagesPreviewSizesId($id = null)
		{
			$this->imagesPreviewSizes = null;
			$this->imagesPreviewSizesId = $id;
			
			return $this;
		}
		
		/**
		 * @return ModuleMultimediaGetImageOperationResponse
		**/
		public function dropImagesPreviewSizes()
		{
			$this->imagesPreviewSizes = null;
			$this->imagesPreviewSizesId = null;
			
			return $this;
		}
		
		public function getMultimediaHost()
		{
			return $this->multimediaHost;
		}
		
		/**
		 * @return ModuleMultimediaGetImageOperationResponse
		**/
		public function setMultimediaHost($multimediaHost)
		{
			$this->multimediaHost = $multimediaHost;
			
			return $this;
		}
	}
?>