<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-08 10:10:45                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformUsersUser extends IdentifiableObject
	{
		protected $email = null;
		protected $password = null;
		protected $nickname = null;
		protected $deleted = null;
		protected $moderation = null;
		protected $banned = null;
		
		public function getEmail()
		{
			return $this->email;
		}
		
		/**
		 * @return PlatformUsersUser
		**/
		public function setEmail($email)
		{
			$this->email = $email;
			
			return $this;
		}
		
		public function getPassword()
		{
			return $this->password;
		}
		
		/**
		 * @return PlatformUsersUser
		**/
		public function setPassword($password)
		{
			$this->password = $password;
			
			return $this;
		}
		
		public function getNickname()
		{
			return $this->nickname;
		}
		
		/**
		 * @return PlatformUsersUser
		**/
		public function setNickname($nickname)
		{
			$this->nickname = $nickname;
			
			return $this;
		}
		
		public function getDeleted()
		{
			return $this->deleted;
		}
		
		public function isDeleted()
		{
			return $this->deleted;
		}
		
		/**
		 * @return PlatformUsersUser
		**/
		public function setDeleted($deleted = false)
		{
			$this->deleted = ($deleted === true);
			
			return $this;
		}
		
		public function getModeration()
		{
			return $this->moderation;
		}
		
		public function isModeration()
		{
			return $this->moderation;
		}
		
		/**
		 * @return PlatformUsersUser
		**/
		public function setModeration($moderation = false)
		{
			$this->moderation = ($moderation === true);
			
			return $this;
		}
		
		public function getBanned()
		{
			return $this->banned;
		}
		
		public function isBanned()
		{
			return $this->banned;
		}
		
		/**
		 * @return PlatformUsersUser
		**/
		public function setBanned($banned = null)
		{
			Assert::isTernaryBase($banned);
			
			$this->banned = $banned;
			
			return $this;
		}
	}
?>