<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-23 11:20:04                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformSmsResponse extends PlatformBaseResponse
	{
		protected $result = false;
		
		public function getResult()
		{
			return $this->result;
		}
		
		public function isResult()
		{
			return $this->result;
		}
		
		/**
		 * @return PlatformSmsResponse
		**/
		public function setResult($result = false)
		{
			$this->result = ($result === true);
			
			return $this;
		}
	}
?>