<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-28 13:42:23                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformSocialPublishedLink extends IdentifiableObject
	{
		protected $flow = null;
		protected $flowId = null;
		protected $description = null;
		protected $linkUrl = null;
		protected $imgUrl = null;
		protected $published = false;
		protected $publishedAt = null;
		protected $createdAt = null;
		
		/**
		 * @return PlatformSocialFlow
		**/
		public function getFlow()
		{
			if (!$this->flow && $this->flowId) {
				$this->flow = PlatformSocialFlow::dao()->getById($this->flowId);
			}
			
			return $this->flow;
		}
		
		public function getFlowId()
		{
			return $this->flow
				? $this->flow->getId()
				: $this->flowId;
		}
		
		/**
		 * @return PlatformSocialPublishedLink
		**/
		public function setFlow(PlatformSocialFlow $flow)
		{
			$this->flow = $flow;
			$this->flowId = $flow ? $flow->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialPublishedLink
		**/
		public function setFlowId($id)
		{
			$this->flow = null;
			$this->flowId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialPublishedLink
		**/
		public function dropFlow()
		{
			$this->flow = null;
			$this->flowId = null;
			
			return $this;
		}
		
		public function getDescription()
		{
			return $this->description;
		}
		
		/**
		 * @return PlatformSocialPublishedLink
		**/
		public function setDescription($description)
		{
			$this->description = $description;
			
			return $this;
		}
		
		public function getLinkUrl()
		{
			return $this->linkUrl;
		}
		
		/**
		 * @return PlatformSocialPublishedLink
		**/
		public function setLinkUrl($linkUrl)
		{
			$this->linkUrl = $linkUrl;
			
			return $this;
		}
		
		public function getImgUrl()
		{
			return $this->imgUrl;
		}
		
		/**
		 * @return PlatformSocialPublishedLink
		**/
		public function setImgUrl($imgUrl)
		{
			$this->imgUrl = $imgUrl;
			
			return $this;
		}
		
		public function getPublished()
		{
			return $this->published;
		}
		
		public function isPublished()
		{
			return $this->published;
		}
		
		/**
		 * @return PlatformSocialPublishedLink
		**/
		public function setPublished($published = null)
		{
			Assert::isTernaryBase($published);
			
			$this->published = $published;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getPublishedAt()
		{
			return $this->publishedAt;
		}
		
		/**
		 * @return PlatformSocialPublishedLink
		**/
		public function setPublishedAt(TimestampTZ $publishedAt = null)
		{
			$this->publishedAt = $publishedAt;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialPublishedLink
		**/
		public function dropPublishedAt()
		{
			$this->publishedAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getCreatedAt()
		{
			return $this->createdAt;
		}
		
		/**
		 * @return PlatformSocialPublishedLink
		**/
		public function setCreatedAt(TimestampTZ $createdAt = null)
		{
			$this->createdAt = $createdAt;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialPublishedLink
		**/
		public function dropCreatedAt()
		{
			$this->createdAt = null;
			
			return $this;
		}
	}
?>