<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-23 14:04:39                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModuleMultimediaRequest extends PlatformBaseRequest
	{
		protected $id = null;
		protected $sourceFile = null;
		protected $preparedFile = null;
		protected $icoFile = null;
		protected $rootDirectory = null;
		protected $name = null;
		protected $title = null;
		protected $description = null;
		protected $tags = null;
		protected $uploadedAt = null;
		protected $mimeType = null;
		
		public function getId()
		{
			return $this->id;
		}
		
		/**
		 * @return ModuleMultimediaRequest
		**/
		public function setId($id)
		{
			$this->id = $id;
			
			return $this;
		}
		
		public function getSourceFile()
		{
			return $this->sourceFile;
		}
		
		/**
		 * @return ModuleMultimediaRequest
		**/
		public function setSourceFile($sourceFile)
		{
			$this->sourceFile = $sourceFile;
			
			return $this;
		}
		
		public function getPreparedFile()
		{
			return $this->preparedFile;
		}
		
		/**
		 * @return ModuleMultimediaRequest
		**/
		public function setPreparedFile($preparedFile)
		{
			$this->preparedFile = $preparedFile;
			
			return $this;
		}
		
		public function getIcoFile()
		{
			return $this->icoFile;
		}
		
		/**
		 * @return ModuleMultimediaRequest
		**/
		public function setIcoFile($icoFile)
		{
			$this->icoFile = $icoFile;
			
			return $this;
		}
		
		public function getRootDirectory()
		{
			return $this->rootDirectory;
		}
		
		/**
		 * @return ModuleMultimediaRequest
		**/
		public function setRootDirectory($rootDirectory)
		{
			$this->rootDirectory = $rootDirectory;
			
			return $this;
		}
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return ModuleMultimediaRequest
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getTitle()
		{
			return $this->title;
		}
		
		/**
		 * @return ModuleMultimediaRequest
		**/
		public function setTitle($title)
		{
			$this->title = $title;
			
			return $this;
		}
		
		public function getDescription()
		{
			return $this->description;
		}
		
		/**
		 * @return ModuleMultimediaRequest
		**/
		public function setDescription($description)
		{
			$this->description = $description;
			
			return $this;
		}
		
		public function getTags()
		{
			return $this->tags;
		}
		
		/**
		 * @return ModuleMultimediaRequest
		**/
		public function setTags($tags)
		{
			$this->tags = $tags;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getUploadedAt()
		{
			return $this->uploadedAt;
		}
		
		/**
		 * @return ModuleMultimediaRequest
		**/
		public function setUploadedAt(TimestampTZ $uploadedAt = null)
		{
			$this->uploadedAt = $uploadedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleMultimediaRequest
		**/
		public function dropUploadedAt()
		{
			$this->uploadedAt = null;
			
			return $this;
		}
		
		public function getMimeType()
		{
			return $this->mimeType;
		}
		
		/**
		 * @return ModuleMultimediaRequest
		**/
		public function setMimeType($mimeType)
		{
			$this->mimeType = $mimeType;
			
			return $this;
		}
	}
?>