<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-01-14 14:07:19                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformSocialAppAdminPage extends IdentifiableObject
	{
		protected $appAdmin = null;
		protected $appAdminId = null;
		protected $name = null;
		protected $category = null;
		protected $pageId = null;
		protected $accessToken = null;
		protected $permissions = null;
		
		/**
		 * @return PlatformSocialAppAdmin
		**/
		public function getAppAdmin()
		{
			if (!$this->appAdmin && $this->appAdminId) {
				$this->appAdmin = PlatformSocialAppAdmin::dao()->getById($this->appAdminId);
			}
			
			return $this->appAdmin;
		}
		
		public function getAppAdminId()
		{
			return $this->appAdmin
				? $this->appAdmin->getId()
				: $this->appAdminId;
		}
		
		/**
		 * @return PlatformSocialAppAdminPage
		**/
		public function setAppAdmin(PlatformSocialAppAdmin $appAdmin)
		{
			$this->appAdmin = $appAdmin;
			$this->appAdminId = $appAdmin ? $appAdmin->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialAppAdminPage
		**/
		public function setAppAdminId($id)
		{
			$this->appAdmin = null;
			$this->appAdminId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialAppAdminPage
		**/
		public function dropAppAdmin()
		{
			$this->appAdmin = null;
			$this->appAdminId = null;
			
			return $this;
		}
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return PlatformSocialAppAdminPage
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getCategory()
		{
			return $this->category;
		}
		
		/**
		 * @return PlatformSocialAppAdminPage
		**/
		public function setCategory($category)
		{
			$this->category = $category;
			
			return $this;
		}
		
		public function getPageId()
		{
			return $this->pageId;
		}
		
		/**
		 * @return PlatformSocialAppAdminPage
		**/
		public function setPageId($pageId)
		{
			$this->pageId = $pageId;
			
			return $this;
		}
		
		public function getAccessToken()
		{
			return $this->accessToken;
		}
		
		/**
		 * @return PlatformSocialAppAdminPage
		**/
		public function setAccessToken($accessToken)
		{
			$this->accessToken = $accessToken;
			
			return $this;
		}
		
		/**
		 * @return Hstore
		**/
		public function getPermissions()
		{
			return $this->permissions;
		}
		
		/**
		 * @return PlatformSocialAppAdminPage
		**/
		public function setPermissions(Hstore $permissions = null)
		{
			$this->permissions = $permissions;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialAppAdminPage
		**/
		public function dropPermissions()
		{
			$this->permissions = null;
			
			return $this;
		}
	}
?>