<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-12 11:36:30                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformUsersBlackIpList extends IdentifiableObject
	{
		protected $ipAddress = null;
		protected $expires = null;
		protected $active = true;
		
		public function getIpAddress()
		{
			return $this->ipAddress;
		}
		
		/**
		 * @return PlatformUsersBlackIpList
		**/
		public function setIpAddress($ipAddress)
		{
			$this->ipAddress = $ipAddress;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getExpires()
		{
			return $this->expires;
		}
		
		/**
		 * @return PlatformUsersBlackIpList
		**/
		public function setExpires(TimestampTZ $expires = null)
		{
			$this->expires = $expires;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersBlackIpList
		**/
		public function dropExpires()
		{
			$this->expires = null;
			
			return $this;
		}
		
		public function getActive()
		{
			return $this->active;
		}
		
		public function isActive()
		{
			return $this->active;
		}
		
		/**
		 * @return PlatformUsersBlackIpList
		**/
		public function setActive($active = null)
		{
			Assert::isTernaryBase($active);
			
			$this->active = $active;
			
			return $this;
		}
	}
?>