<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-08 12:44:23                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformUsersAuthCommon extends IdentifiableObject
	{
		protected $userInfo = null;
		protected $userInfoId = null;
		protected $authType = null;
		protected $authTypeId = null;
		protected $token = null;
		protected $refreshToken = null;
		protected $profileUrl = null;
		
		/**
		 * @return PlatformUsersUserInfo
		**/
		public function getUserInfo()
		{
			if (!$this->userInfo && $this->userInfoId) {
				$this->userInfo = PlatformUsersUserInfo::dao()->getById($this->userInfoId);
			}
			
			return $this->userInfo;
		}
		
		public function getUserInfoId()
		{
			return $this->userInfo
				? $this->userInfo->getId()
				: $this->userInfoId;
		}
		
		/**
		 * @return PlatformUsersAuthCommon
		**/
		public function setUserInfo(PlatformUsersUserInfo $userInfo)
		{
			$this->userInfo = $userInfo;
			$this->userInfoId = $userInfo ? $userInfo->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAuthCommon
		**/
		public function setUserInfoId($id)
		{
			$this->userInfo = null;
			$this->userInfoId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAuthCommon
		**/
		public function dropUserInfo()
		{
			$this->userInfo = null;
			$this->userInfoId = null;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAuthType
		**/
		public function getAuthType()
		{
			if (!$this->authType && $this->authTypeId) {
				$this->authType = PlatformUsersAuthType::dao()->getById($this->authTypeId);
			}
			
			return $this->authType;
		}
		
		public function getAuthTypeId()
		{
			return $this->authType
				? $this->authType->getId()
				: $this->authTypeId;
		}
		
		/**
		 * @return PlatformUsersAuthCommon
		**/
		public function setAuthType(PlatformUsersAuthType $authType)
		{
			$this->authType = $authType;
			$this->authTypeId = $authType ? $authType->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAuthCommon
		**/
		public function setAuthTypeId($id)
		{
			$this->authType = null;
			$this->authTypeId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAuthCommon
		**/
		public function dropAuthType()
		{
			$this->authType = null;
			$this->authTypeId = null;
			
			return $this;
		}
		
		public function getToken()
		{
			return $this->token;
		}
		
		/**
		 * @return PlatformUsersAuthCommon
		**/
		public function setToken($token)
		{
			$this->token = $token;
			
			return $this;
		}
		
		public function getRefreshToken()
		{
			return $this->refreshToken;
		}
		
		/**
		 * @return PlatformUsersAuthCommon
		**/
		public function setRefreshToken($refreshToken)
		{
			$this->refreshToken = $refreshToken;
			
			return $this;
		}
		
		public function getProfileUrl()
		{
			return $this->profileUrl;
		}
		
		/**
		 * @return PlatformUsersAuthCommon
		**/
		public function setProfileUrl($profileUrl)
		{
			$this->profileUrl = $profileUrl;
			
			return $this;
		}
	}
?>