<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-06-14 09:00:40                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoMultimediaUnsorted extends IdentifiableObject
	{
		protected $tags = null;
		protected $description = null;
		protected $title = null;
		protected $createdAt = null;
		
		public function getTags()
		{
			return $this->tags;
		}
		
		/**
		 * @return MultimediaUnsorted
		**/
		public function setTags($tags)
		{
			$this->tags = $tags;
			
			return $this;
		}
		
		public function getDescription()
		{
			return $this->description;
		}
		
		/**
		 * @return MultimediaUnsorted
		**/
		public function setDescription($description)
		{
			$this->description = $description;
			
			return $this;
		}
		
		public function getTitle()
		{
			return $this->title;
		}
		
		/**
		 * @return MultimediaUnsorted
		**/
		public function setTitle($title)
		{
			$this->title = $title;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getCreatedAt()
		{
			return $this->createdAt;
		}
		
		/**
		 * @return MultimediaUnsorted
		**/
		public function setCreatedAt(TimestampTZ $createdAt = null)
		{
			$this->createdAt = $createdAt;
			
			return $this;
		}
		
		/**
		 * @return MultimediaUnsorted
		**/
		public function dropCreatedAt()
		{
			$this->createdAt = null;
			
			return $this;
		}
	}
?>