<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-04-13 14:17:57                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModuleArticleResponse extends PlatformBaseRequest
	{
		protected $articleId = null;
		protected $projectId = null;
		protected $articleDraftId = null;
		protected $articlePublishedId = null;
		protected $publishedAt = null;
		protected $published = null;
		protected $rubrics = null;
		protected $title = null;
		protected $anons = null;
		protected $text = null;
		protected $metaDescription = null;
		protected $metaKeywords = null;
		protected $createdAt = null;
		protected $modifiedAt = null;
		protected $preview = 'NULL';
		protected $author = null;
		protected $adminId = null;
		protected $images = null;
		
		public function getArticleId()
		{
			return $this->articleId;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setArticleId($articleId)
		{
			$this->articleId = $articleId;
			
			return $this;
		}
		
		public function getProjectId()
		{
			return $this->projectId;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setProjectId($projectId)
		{
			$this->projectId = $projectId;
			
			return $this;
		}
		
		public function getArticleDraftId()
		{
			return $this->articleDraftId;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setArticleDraftId($articleDraftId)
		{
			$this->articleDraftId = $articleDraftId;
			
			return $this;
		}
		
		public function getArticlePublishedId()
		{
			return $this->articlePublishedId;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setArticlePublishedId($articlePublishedId)
		{
			$this->articlePublishedId = $articlePublishedId;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getPublishedAt()
		{
			return $this->publishedAt;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setPublishedAt(TimestampTZ $publishedAt = null)
		{
			$this->publishedAt = $publishedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function dropPublishedAt()
		{
			$this->publishedAt = null;
			
			return $this;
		}
		
		public function getPublished()
		{
			return $this->published;
		}
		
		public function isPublished()
		{
			return $this->published;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setPublished($published = null)
		{
			Assert::isTernaryBase($published);
			
			$this->published = $published;
			
			return $this;
		}
		
		/**
		 * @return Hstore
		**/
		public function getRubrics()
		{
			return $this->rubrics;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setRubrics(Hstore $rubrics = null)
		{
			$this->rubrics = $rubrics;
			
			return $this;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function dropRubrics()
		{
			$this->rubrics = null;
			
			return $this;
		}
		
		public function getTitle()
		{
			return $this->title;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setTitle($title)
		{
			$this->title = $title;
			
			return $this;
		}
		
		public function getAnons()
		{
			return $this->anons;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setAnons($anons)
		{
			$this->anons = $anons;
			
			return $this;
		}
		
		public function getText()
		{
			return $this->text;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setText($text)
		{
			$this->text = $text;
			
			return $this;
		}
		
		public function getMetaDescription()
		{
			return $this->metaDescription;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setMetaDescription($metaDescription)
		{
			$this->metaDescription = $metaDescription;
			
			return $this;
		}
		
		public function getMetaKeywords()
		{
			return $this->metaKeywords;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setMetaKeywords($metaKeywords)
		{
			$this->metaKeywords = $metaKeywords;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getCreatedAt()
		{
			return $this->createdAt;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setCreatedAt(TimestampTZ $createdAt = null)
		{
			$this->createdAt = $createdAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function dropCreatedAt()
		{
			$this->createdAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getModifiedAt()
		{
			return $this->modifiedAt;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setModifiedAt(TimestampTZ $modifiedAt = null)
		{
			$this->modifiedAt = $modifiedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function dropModifiedAt()
		{
			$this->modifiedAt = null;
			
			return $this;
		}
		
		public function getPreview()
		{
			return $this->preview;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setPreview($preview)
		{
			$this->preview = $preview;
			
			return $this;
		}
		
		public function getAuthor()
		{
			return $this->author;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setAuthor($author)
		{
			$this->author = $author;
			
			return $this;
		}
		
		public function getAdminId()
		{
			return $this->adminId;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setAdminId($adminId)
		{
			$this->adminId = $adminId;
			
			return $this;
		}
		
		/**
		 * @return Hstore
		**/
		public function getImages()
		{
			return $this->images;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function setImages(Hstore $images = null)
		{
			$this->images = $images;
			
			return $this;
		}
		
		/**
		 * @return ModuleArticleResponse
		**/
		public function dropImages()
		{
			$this->images = null;
			
			return $this;
		}
	}
?>