<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-08 13:10:19                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformCommonProject extends IdentifiableObject
	{
		protected $name = null;
		protected $title = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return PlatformCommonProject
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getTitle()
		{
			return $this->title;
		}
		
		/**
		 * @return PlatformCommonProject
		**/
		public function setTitle($title)
		{
			$this->title = $title;
			
			return $this;
		}
	}
?>