<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-23 12:25:38                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformSendCodeRequest extends PlatformBaseRequest
	{
		protected $code = null;
		protected $type = null;
		protected $typeId = null;
		
		public function getCode()
		{
			return $this->code;
		}
		
		/**
		 * @return PlatformSendCodeRequest
		**/
		public function setCode($code)
		{
			$this->code = $code;
			
			return $this;
		}
		
		/**
		 * @return PlatformUsersAdminCodeTypeEnum
		**/
		public function getType()
		{
			if (!$this->type && $this->typeId) {
				$this->type = new PlatformUsersAdminCodeTypeEnum($this->typeId);
			}
			
			return $this->type;
		}
		
		public function getTypeId()
		{
			return $this->type
				? $this->type->getId()
				: $this->typeId;
		}
		
		/**
		 * @return PlatformSendCodeRequest
		**/
		public function setType(PlatformUsersAdminCodeTypeEnum $type)
		{
			$this->type = $type;
			$this->typeId = $type ? $type->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformSendCodeRequest
		**/
		public function setTypeId($id)
		{
			$this->type = null;
			$this->typeId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformSendCodeRequest
		**/
		public function dropType()
		{
			$this->type = null;
			$this->typeId = null;
			
			return $this;
		}
	}
?>