<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-12-09 09:15:21                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformCommonProjectModule extends IdentifiableObject
	{
		protected $module = null;
		protected $moduleId = null;
		protected $project = null;
		protected $projectId = null;
		protected $disabled = null;
		
		/**
		 * @return PlatformCommonModule
		**/
		public function getModule()
		{
			if (!$this->module && $this->moduleId) {
				$this->module = PlatformCommonModule::dao()->getById($this->moduleId);
			}
			
			return $this->module;
		}
		
		public function getModuleId()
		{
			return $this->module
				? $this->module->getId()
				: $this->moduleId;
		}
		
		/**
		 * @return PlatformCommonProjectModule
		**/
		public function setModule(PlatformCommonModule $module)
		{
			$this->module = $module;
			$this->moduleId = $module ? $module->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonProjectModule
		**/
		public function setModuleId($id)
		{
			$this->module = null;
			$this->moduleId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonProjectModule
		**/
		public function dropModule()
		{
			$this->module = null;
			$this->moduleId = null;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonProject
		**/
		public function getProject()
		{
			if (!$this->project && $this->projectId) {
				$this->project = PlatformCommonProject::dao()->getById($this->projectId);
			}
			
			return $this->project;
		}
		
		public function getProjectId()
		{
			return $this->project
				? $this->project->getId()
				: $this->projectId;
		}
		
		/**
		 * @return PlatformCommonProjectModule
		**/
		public function setProject(PlatformCommonProject $project)
		{
			$this->project = $project;
			$this->projectId = $project ? $project->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonProjectModule
		**/
		public function setProjectId($id)
		{
			$this->project = null;
			$this->projectId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformCommonProjectModule
		**/
		public function dropProject()
		{
			$this->project = null;
			$this->projectId = null;
			
			return $this;
		}
		
		public function getDisabled()
		{
			return $this->disabled;
		}
		
		public function isDisabled()
		{
			return $this->disabled;
		}
		
		/**
		 * @return PlatformCommonProjectModule
		**/
		public function setDisabled($disabled = null)
		{
			Assert::isTernaryBase($disabled);
			
			$this->disabled = $disabled;
			
			return $this;
		}
	}
?>