<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-09 12:39:08                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModuleNewsResponse extends PlatformBaseRequest
	{
		protected $newsId = null;
		protected $projectId = null;
		protected $newsDraftId = null;
		protected $newsPublishedId = null;
		protected $publishedAt = null;
		protected $published = null;
		protected $rubrics = null;
		protected $title = null;
		protected $anons = null;
		protected $text = null;
		protected $metaDescription = null;
		protected $metaKeywords = null;
		protected $createdAt = null;
		protected $modifiedAt = null;
		protected $preview = 'NULL';
		protected $adminId = null;
		
		public function getNewsId()
		{
			return $this->newsId;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setNewsId($newsId)
		{
			$this->newsId = $newsId;
			
			return $this;
		}
		
		public function getProjectId()
		{
			return $this->projectId;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setProjectId($projectId)
		{
			$this->projectId = $projectId;
			
			return $this;
		}
		
		public function getNewsDraftId()
		{
			return $this->newsDraftId;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setNewsDraftId($newsDraftId)
		{
			$this->newsDraftId = $newsDraftId;
			
			return $this;
		}
		
		public function getNewsPublishedId()
		{
			return $this->newsPublishedId;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setNewsPublishedId($newsPublishedId)
		{
			$this->newsPublishedId = $newsPublishedId;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getPublishedAt()
		{
			return $this->publishedAt;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setPublishedAt(TimestampTZ $publishedAt = null)
		{
			$this->publishedAt = $publishedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function dropPublishedAt()
		{
			$this->publishedAt = null;
			
			return $this;
		}
		
		public function getPublished()
		{
			return $this->published;
		}
		
		public function isPublished()
		{
			return $this->published;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setPublished($published = null)
		{
			Assert::isTernaryBase($published);
			
			$this->published = $published;
			
			return $this;
		}
		
		/**
		 * @return Hstore
		**/
		public function getRubrics()
		{
			return $this->rubrics;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setRubrics(Hstore $rubrics = null)
		{
			$this->rubrics = $rubrics;
			
			return $this;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function dropRubrics()
		{
			$this->rubrics = null;
			
			return $this;
		}
		
		public function getTitle()
		{
			return $this->title;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setTitle($title)
		{
			$this->title = $title;
			
			return $this;
		}
		
		public function getAnons()
		{
			return $this->anons;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setAnons($anons)
		{
			$this->anons = $anons;
			
			return $this;
		}
		
		public function getText()
		{
			return $this->text;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setText($text)
		{
			$this->text = $text;
			
			return $this;
		}
		
		public function getMetaDescription()
		{
			return $this->metaDescription;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setMetaDescription($metaDescription)
		{
			$this->metaDescription = $metaDescription;
			
			return $this;
		}
		
		public function getMetaKeywords()
		{
			return $this->metaKeywords;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setMetaKeywords($metaKeywords)
		{
			$this->metaKeywords = $metaKeywords;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getCreatedAt()
		{
			return $this->createdAt;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setCreatedAt(TimestampTZ $createdAt = null)
		{
			$this->createdAt = $createdAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function dropCreatedAt()
		{
			$this->createdAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getModifiedAt()
		{
			return $this->modifiedAt;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setModifiedAt(TimestampTZ $modifiedAt = null)
		{
			$this->modifiedAt = $modifiedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function dropModifiedAt()
		{
			$this->modifiedAt = null;
			
			return $this;
		}
		
		public function getPreview()
		{
			return $this->preview;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setPreview($preview)
		{
			$this->preview = $preview;
			
			return $this;
		}
		
		public function getAdminId()
		{
			return $this->adminId;
		}
		
		/**
		 * @return ModuleNewsResponse
		**/
		public function setAdminId($adminId)
		{
			$this->adminId = $adminId;
			
			return $this;
		}
	}
?>