<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2016-04-11 09:08:09                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPlatformSocialPublishedLinkData extends IdentifiableObject
	{
		protected $publishedLink = null;
		protected $publishedLinkId = null;
		protected $appAdminPages = null;
		protected $appAdminPagesId = null;
		protected $appAdminGroup = null;
		protected $appAdminGroupId = null;
		protected $socialNetwork = null;
		protected $postId = null;
		
		/**
		 * @return PlatformSocialPublishedLink
		**/
		public function getPublishedLink()
		{
			if (!$this->publishedLink && $this->publishedLinkId) {
				$this->publishedLink = PlatformSocialPublishedLink::dao()->getById($this->publishedLinkId);
			}
			
			return $this->publishedLink;
		}
		
		public function getPublishedLinkId()
		{
			return $this->publishedLink
				? $this->publishedLink->getId()
				: $this->publishedLinkId;
		}
		
		/**
		 * @return PlatformSocialPublishedLinkData
		**/
		public function setPublishedLink(PlatformSocialPublishedLink $publishedLink)
		{
			$this->publishedLink = $publishedLink;
			$this->publishedLinkId = $publishedLink ? $publishedLink->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialPublishedLinkData
		**/
		public function setPublishedLinkId($id)
		{
			$this->publishedLink = null;
			$this->publishedLinkId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialPublishedLinkData
		**/
		public function dropPublishedLink()
		{
			$this->publishedLink = null;
			$this->publishedLinkId = null;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialAppAdminPage
		**/
		public function getAppAdminPages()
		{
			if (!$this->appAdminPages && $this->appAdminPagesId) {
				$this->appAdminPages = PlatformSocialAppAdminPage::dao()->getById($this->appAdminPagesId);
			}
			
			return $this->appAdminPages;
		}
		
		public function getAppAdminPagesId()
		{
			return $this->appAdminPages
				? $this->appAdminPages->getId()
				: $this->appAdminPagesId;
		}
		
		/**
		 * @return PlatformSocialPublishedLinkData
		**/
		public function setAppAdminPages(PlatformSocialAppAdminPage $appAdminPages = null)
		{
			$this->appAdminPages = $appAdminPages;
			$this->appAdminPagesId = $appAdminPages ? $appAdminPages->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialPublishedLinkData
		**/
		public function setAppAdminPagesId($id = null)
		{
			$this->appAdminPages = null;
			$this->appAdminPagesId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialPublishedLinkData
		**/
		public function dropAppAdminPages()
		{
			$this->appAdminPages = null;
			$this->appAdminPagesId = null;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialAppAdminGroup
		**/
		public function getAppAdminGroup()
		{
			if (!$this->appAdminGroup && $this->appAdminGroupId) {
				$this->appAdminGroup = PlatformSocialAppAdminGroup::dao()->getById($this->appAdminGroupId);
			}
			
			return $this->appAdminGroup;
		}
		
		public function getAppAdminGroupId()
		{
			return $this->appAdminGroup
				? $this->appAdminGroup->getId()
				: $this->appAdminGroupId;
		}
		
		/**
		 * @return PlatformSocialPublishedLinkData
		**/
		public function setAppAdminGroup(PlatformSocialAppAdminGroup $appAdminGroup = null)
		{
			$this->appAdminGroup = $appAdminGroup;
			$this->appAdminGroupId = $appAdminGroup ? $appAdminGroup->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialPublishedLinkData
		**/
		public function setAppAdminGroupId($id = null)
		{
			$this->appAdminGroup = null;
			$this->appAdminGroupId = $id;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialPublishedLinkData
		**/
		public function dropAppAdminGroup()
		{
			$this->appAdminGroup = null;
			$this->appAdminGroupId = null;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialNameEnum
		**/
		public function getSocialNetwork()
		{
			return $this->socialNetwork;
		}
		
		/**
		 * @return PlatformSocialPublishedLinkData
		**/
		public function setSocialNetwork(PlatformSocialNameEnum $socialNetwork)
		{
			$this->socialNetwork = $socialNetwork;
			
			return $this;
		}
		
		/**
		 * @return PlatformSocialPublishedLinkData
		**/
		public function dropSocialNetwork()
		{
			$this->socialNetwork = null;
			
			return $this;
		}
		
		public function getPostId()
		{
			return $this->postId;
		}
		
		/**
		 * @return PlatformSocialPublishedLinkData
		**/
		public function setPostId($postId)
		{
			$this->postId = $postId;
			
			return $this;
		}
	}
?>