<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-03-18 13:48:40                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModuleMultimediaSearchOperationRequest extends ModuleMultimediaRequest
	{
		protected $draw = null;
		protected $offset = null;
		protected $limit = null;
		protected $ofUploadedAt = null;
		protected $toUploadedAt = null;
		
		public function getDraw()
		{
			return $this->draw;
		}
		
		/**
		 * @return ModuleMultimediaSearchOperationRequest
		**/
		public function setDraw($draw)
		{
			$this->draw = $draw;
			
			return $this;
		}
		
		public function getOffset()
		{
			return $this->offset;
		}
		
		/**
		 * @return ModuleMultimediaSearchOperationRequest
		**/
		public function setOffset($offset)
		{
			$this->offset = $offset;
			
			return $this;
		}
		
		public function getLimit()
		{
			return $this->limit;
		}
		
		/**
		 * @return ModuleMultimediaSearchOperationRequest
		**/
		public function setLimit($limit)
		{
			$this->limit = $limit;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getOfUploadedAt()
		{
			return $this->ofUploadedAt;
		}
		
		/**
		 * @return ModuleMultimediaSearchOperationRequest
		**/
		public function setOfUploadedAt(TimestampTZ $ofUploadedAt = null)
		{
			$this->ofUploadedAt = $ofUploadedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleMultimediaSearchOperationRequest
		**/
		public function dropOfUploadedAt()
		{
			$this->ofUploadedAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getToUploadedAt()
		{
			return $this->toUploadedAt;
		}
		
		/**
		 * @return ModuleMultimediaSearchOperationRequest
		**/
		public function setToUploadedAt(TimestampTZ $toUploadedAt = null)
		{
			$this->toUploadedAt = $toUploadedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleMultimediaSearchOperationRequest
		**/
		public function dropToUploadedAt()
		{
			$this->toUploadedAt = null;
			
			return $this;
		}
	}
?>