<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2015-02-02 12:28:53                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoModuleArticleSearchOperationRequest extends ModuleArticleRequest
	{
		protected $draw = null;
		protected $offset = null;
		protected $limit = null;
		protected $ofCreatedAt = null;
		protected $toCreatedAt = null;
		protected $ofModifiedAt = null;
		protected $toModifiedAt = null;
		protected $ofPublishedAt = null;
		protected $toPublishedAt = null;
		
		public function getDraw()
		{
			return $this->draw;
		}
		
		/**
		 * @return ModuleArticleSearchOperationRequest
		**/
		public function setDraw($draw)
		{
			$this->draw = $draw;
			
			return $this;
		}
		
		public function getOffset()
		{
			return $this->offset;
		}
		
		/**
		 * @return ModuleArticleSearchOperationRequest
		**/
		public function setOffset($offset)
		{
			$this->offset = $offset;
			
			return $this;
		}
		
		public function getLimit()
		{
			return $this->limit;
		}
		
		/**
		 * @return ModuleArticleSearchOperationRequest
		**/
		public function setLimit($limit)
		{
			$this->limit = $limit;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getOfCreatedAt()
		{
			return $this->ofCreatedAt;
		}
		
		/**
		 * @return ModuleArticleSearchOperationRequest
		**/
		public function setOfCreatedAt(TimestampTZ $ofCreatedAt = null)
		{
			$this->ofCreatedAt = $ofCreatedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleArticleSearchOperationRequest
		**/
		public function dropOfCreatedAt()
		{
			$this->ofCreatedAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getToCreatedAt()
		{
			return $this->toCreatedAt;
		}
		
		/**
		 * @return ModuleArticleSearchOperationRequest
		**/
		public function setToCreatedAt(TimestampTZ $toCreatedAt = null)
		{
			$this->toCreatedAt = $toCreatedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleArticleSearchOperationRequest
		**/
		public function dropToCreatedAt()
		{
			$this->toCreatedAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getOfModifiedAt()
		{
			return $this->ofModifiedAt;
		}
		
		/**
		 * @return ModuleArticleSearchOperationRequest
		**/
		public function setOfModifiedAt(TimestampTZ $ofModifiedAt = null)
		{
			$this->ofModifiedAt = $ofModifiedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleArticleSearchOperationRequest
		**/
		public function dropOfModifiedAt()
		{
			$this->ofModifiedAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getToModifiedAt()
		{
			return $this->toModifiedAt;
		}
		
		/**
		 * @return ModuleArticleSearchOperationRequest
		**/
		public function setToModifiedAt(TimestampTZ $toModifiedAt = null)
		{
			$this->toModifiedAt = $toModifiedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleArticleSearchOperationRequest
		**/
		public function dropToModifiedAt()
		{
			$this->toModifiedAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getOfPublishedAt()
		{
			return $this->ofPublishedAt;
		}
		
		/**
		 * @return ModuleArticleSearchOperationRequest
		**/
		public function setOfPublishedAt(TimestampTZ $ofPublishedAt = null)
		{
			$this->ofPublishedAt = $ofPublishedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleArticleSearchOperationRequest
		**/
		public function dropOfPublishedAt()
		{
			$this->ofPublishedAt = null;
			
			return $this;
		}
		
		/**
		 * @return TimestampTZ
		**/
		public function getToPublishedAt()
		{
			return $this->toPublishedAt;
		}
		
		/**
		 * @return ModuleArticleSearchOperationRequest
		**/
		public function setToPublishedAt(TimestampTZ $toPublishedAt = null)
		{
			$this->toPublishedAt = $toPublishedAt;
			
			return $this;
		}
		
		/**
		 * @return ModuleArticleSearchOperationRequest
		**/
		public function dropToPublishedAt()
		{
			$this->toPublishedAt = null;
			
			return $this;
		}
	}
?>